<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2c060ec0-aa2e-4a8f-8da4-90a049c0a4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='CerrarDialogoCardMail();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.labelGLNegroMensaje.text-center > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe9a036e-d682-4006-8373-b76bb85396ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/boton-aceptar.png</value>
      <webElementGuid>982fe5c5-a52e-4208-928c-6dfc5b3c65a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CerrarDialogoCardMail();</value>
      <webElementGuid>0df02573-4c5c-42d3-92ad-1622cb7da0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecomendacionNavegadorMail&quot;)/div[@class=&quot;dialog-cardMail&quot;]/div[1]/div[@class=&quot;col-md-12 col-xs-12 text-center&quot;]/p[@class=&quot;labelGLNegroMensaje text-center&quot;]/img[1]</value>
      <webElementGuid>d061849f-4ed5-4533-9eb1-2e99cfc52d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='CerrarDialogoCardMail();']</value>
      <webElementGuid>9512c66d-24ad-4247-aaac-771ce8a6d1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RecomendacionNavegadorMail']/div/div/div/p/img</value>
      <webElementGuid>21fa466b-1947-4f20-8edd-e3aee4078789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
      <webElementGuid>2ff724cb-2113-484d-8019-c135aae9dc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/boton-aceptar.png']</value>
      <webElementGuid>d7d220b5-9a55-4e49-9f21-d4664bf7a98f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
