<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Nacimiento no pertenece al cedu_1a96b4</name>
   <tag></tag>
   <elementGuidId>9fcbf24f-5de6-4296-802e-8f32d4f39b09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FechaNacimiento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FechaNacimiento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5aaf5f5-a7af-47f7-b4f1-c35f276d0f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d825246-8dd9-4348-af0f-531b7a010c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0458e4a2-4dd5-48e6-b1a0-9944095d6cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Salud must be a date.</value>
      <webElementGuid>9b69f851-1e21-4f32-91eb-6fca823c174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Fecha de Nacimiento es obligatorio</value>
      <webElementGuid>33efb41f-64f5-4dff-8c61-d41d83dc4626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>5947ae94-cb81-4820-ab32-f9317ddccd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>14861cb9-7ba3-48dc-bf26-f74b36333382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>ddae7983-14c0-428e-a4b7-ed7fcb7d777e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fecha de nacimiento dd/mm/aaaa</value>
      <webElementGuid>0adb64fb-df69-4a95-8796-240fe9a3e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d59cd6f7-96b6-4898-8790-bd5d8aa9d818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/01/0001 12:00:00 a. m.</value>
      <webElementGuid>ec373419-233e-4f8b-805a-626818cad815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4f9b8b10-bfc1-4052-affe-3f545ceef7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FechaNacimiento&quot;)</value>
      <webElementGuid>ab58b16e-0686-4622-a5c0-c03701c54e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FechaNacimiento']</value>
      <webElementGuid>85b6d1ad-43b0-4386-a61a-6a26cf4168f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div/input</value>
      <webElementGuid>f91ea5b6-482b-4dd0-a316-0f103b17a4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>61f48308-4c5e-4cb2-a065-0d76ae4593db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FechaNacimiento' and @name = 'FechaNacimiento' and @placeholder = 'Fecha de nacimiento dd/mm/aaaa' and @type = 'text']</value>
      <webElementGuid>648604ab-dd76-409d-8e20-e158a3a4722a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
