<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_meses_Continuar</name>
   <tag></tag>
   <elementGuidId>ddf92869-c088-4056-89bc-132f454914ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Continuar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Continuar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>922671b2-98a3-4c25-828c-f2c95f469086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/Aplica-ahora.png</value>
      <webElementGuid>c34f2192-b0f6-4c02-9588-6de459c1348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bntAplicaAhora</value>
      <webElementGuid>8122df69-aa3f-4a15-ba2e-d2b6e3bf1eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>fdfc2a16-e389-46d0-ac5b-bd512704a54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Continuar&quot;)</value>
      <webElementGuid>81941fa9-142a-4f68-ba14-be7cff246ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Continuar']</value>
      <webElementGuid>69c965a4-659f-4b9f-bd1b-76885f295439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/div[2]/div/div[2]/div/img</value>
      <webElementGuid>3eeef628-8146-4f7e-a2e6-1270caa2a89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>18b19e77-258f-43f0-a7aa-c8722e575bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/Aplica-ahora.png' and @id = 'Continuar']</value>
      <webElementGuid>63b7a80b-e991-4129-832a-b600133f9a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
