<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cerrar</name>
   <tag></tag>
   <elementGuidId>91e809ba-cc07-4b36-9d2f-2e569a9ec768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-message/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-flat-button.mat-button-base.mat-primary.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1ab64e3-97fc-4425-abef-ef02bad4ca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>191f8807-00fd-432b-85fd-3ec976b0a3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerrar</value>
      <webElementGuid>caa4ef42-acac-49ac-8d54-ae9a5206defc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-message[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;text-center flex-column align-items-center justify-content-center p-5&quot;]/div[@class=&quot;mt-4 text-center&quot;]/button[@class=&quot;mat-flat-button mat-button-base mat-primary cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>88d30fdd-14f7-4435-978b-c212e927f797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-message/div/div[2]/button/span</value>
      <webElementGuid>52822fe2-d552-4f3a-9ac9-806ec7e17301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::span[3]</value>
      <webElementGuid>2c9b403e-0ad1-46aa-bbcf-6f7b0169a55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar clave nueva'])[1]/following::span[4]</value>
      <webElementGuid>fa0821e9-544e-49fb-9570-4708fadc15e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerrar']/parent::*</value>
      <webElementGuid>0c5f2a46-06a1-4d38-b18c-3288de7468ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button/span</value>
      <webElementGuid>686f1ddb-7f48-4096-a7a6-0c0fe6e161dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cerrar' or . = 'Cerrar')]</value>
      <webElementGuid>8624ff5d-2246-4f6c-8c0e-00b35f76c999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
