<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ofertar</name>
   <tag></tag>
   <elementGuidId>b0062e75-e971-483f-8ea1-da9f883d9fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.oferta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9a3581d-28f9-4081-95e5-069854d47844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88e850f7-0632-4065-9b71-e110a1509642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success oferta</value>
      <webElementGuid>d627c78e-3fca-4881-b2ea-123c259d295e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PresentarOfertasGeneradas('Alia Inmediato', null, null, null, 700.00, 'ALIINM', true);</value>
      <webElementGuid>30360ad9-3ff8-4f37-9b94-20c4e81cfe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>00f65314-2431-4158-b7cb-bd02c046407b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ofertar</value>
      <webElementGuid>0f6b2638-9b73-43af-97f8-a9dc73a4c4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementosOfertas&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;box box-default&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;info-box&quot;]/div[@class=&quot;info-box-content&quot;]/div[@class=&quot;info-box-number&quot;]/span[1]/button[@class=&quot;btn btn-success oferta&quot;]</value>
      <webElementGuid>ca9eef37-19f3-4651-bc0e-8ac09e0aead8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>c06ed8d5-02be-4bf2-8fa1-8708d7d5a2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementosOfertas']/div[3]/div/div[2]/div/div/div/span/button</value>
      <webElementGuid>eb8be4b1-2aa5-4763-ba05-b46621baa57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 700.00'])[1]/following::button[1]</value>
      <webElementGuid>5039907f-5b77-4e7c-98e8-34275b56b22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alia Inmediato'])[1]/following::button[2]</value>
      <webElementGuid>40e75b9d-50a6-4dfd-833a-58cadc753e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UniCrédito Análisis'])[1]/preceding::button[1]</value>
      <webElementGuid>7411d558-7c06-4839-bd78-91edb9f710ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ofertar']/parent::*</value>
      <webElementGuid>faa48bc6-06c6-4cdf-8926-0206cbaba851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>cc559eb8-de46-43ef-95d2-223b1a5da6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ofertar' or . = 'Ofertar')]</value>
      <webElementGuid>f4468bd4-7366-4380-af26-383301057803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
