<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PrimerNombre</name>
   <tag></tag>
   <elementGuidId>7203556c-183a-4619-ad53-00aec4083c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IdPrimerNombre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdPrimerNombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d6bfbe1-1457-4269-b2a9-a48b04bb7b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control LabelNegro </value>
      <webElementGuid>33b7569c-b7cd-48d7-afd5-c1e5a8ddd4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>491c84ed-183f-4474-9a76-b4295ab239cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PrimerNombre field is required.</value>
      <webElementGuid>bb09eb12-5ff5-4b47-b456-e2c14cae322f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdPrimerNombre</value>
      <webElementGuid>6804e8ee-a857-4d26-8142-99d72bc9a1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimerNombre</value>
      <webElementGuid>013f1982-b4d0-4907-a153-ea7a56a0b7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f3250c98-c189-4c3b-93d0-4f909e6bd47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>620704b0-e331-4c16-87df-fd8731693384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdPrimerNombre&quot;)</value>
      <webElementGuid>a6411b6c-f420-4663-8224-b92331fe1db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IdPrimerNombre']</value>
      <webElementGuid>a70d0c60-8f71-4994-8c40-0da05e1d65b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmMicroCreditoInternet']/div[3]/div/div/div[3]/div/input</value>
      <webElementGuid>38685103-0a24-4a11-9e98-17db460bab8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>30619dad-9d80-44ea-91dc-b1b5116349b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IdPrimerNombre' and @name = 'PrimerNombre' and @type = 'text']</value>
      <webElementGuid>ab702afc-04ed-4056-874b-a01c41516488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
