<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresa tu correo electrnico_Autorizacion</name>
   <tag></tag>
   <elementGuidId>62cd467d-e15a-4fb6-9e18-f6c7fb9caa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Autorizacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Autorizacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b855b8e4-8799-46f2-a658-b503bc12f106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85ad144e-ac9e-400f-8c59-69ca334b7e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Autorizacion field is required.</value>
      <webElementGuid>8133073b-6298-4411-88b0-8db59501abf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>f21c27d9-de4b-4d64-8d60-9ec10adfad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>cdc8e564-4bdb-46a1-a56c-e7122fe427fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.setCustomValidity(validity.valueMissing ? 'Por favor autorizar que sus datos sean consultados' : '');</value>
      <webElementGuid>a7c72147-59e2-4f5f-87a5-252140052b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fbc6172d-094d-47a8-a790-8e276a3cc3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>13e93b24-77d3-4ff4-8af1-4ab5d809baa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84c927a4-da04-451b-9689-d283104615ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Autorizacion&quot;)</value>
      <webElementGuid>3ec9f6cc-952a-4ecf-a4e2-b5abbb985a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Autorizacion']</value>
      <webElementGuid>bfc15329-1195-450d-9407-36b78025d9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmMicroCreditoInternet']/div[3]/div[7]/div[2]/div/input</value>
      <webElementGuid>9d3bc713-7360-43ef-9e5c-8a914eb06e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>a6df9b68-d41c-4f84-a407-3d241269b792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Autorizacion' and @name = 'Autorizacion' and @type = 'checkbox']</value>
      <webElementGuid>0d81eff5-ce41-43eb-8fac-0653823cb8f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
