<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PrimerApellido</name>
   <tag></tag>
   <elementGuidId>109e59f7-f646-48f9-ac0e-500e91dce1ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PrimerApellido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PrimerApellido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2ceb6ef-6c62-4375-a19d-d23dcc1018dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> form-control LabelNegro</value>
      <webElementGuid>0a8135fb-756f-4031-a1ec-6f8ac5ee71bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1ef7d33-2d12-4db3-9417-6acc0c28e8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PrimerApellido field is required.</value>
      <webElementGuid>79273a20-5f5f-4379-8a0a-994ef21be9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrimerApellido</value>
      <webElementGuid>ca0d8c61-f823-456d-a512-c61cbfbd76b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimerApellido</value>
      <webElementGuid>e0b44e87-a8bb-4965-a259-c91462373b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>aad44096-03f0-4463-8d4c-d43086341a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fe00872-7e80-47fc-a883-1ca2591f1a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrimerApellido&quot;)</value>
      <webElementGuid>caad61ef-f88f-452d-a9b3-591d2ab4d96f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PrimerApellido']</value>
      <webElementGuid>f8198e35-419d-4fd6-8125-f554dcbbc3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmMicroCreditoInternet']/div[3]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>5bbb42e6-8fc1-4234-a6ad-6a0d85b6319d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c47b7706-8cdf-4d02-8776-fcbd8119d43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PrimerApellido' and @name = 'PrimerApellido' and @type = 'text']</value>
      <webElementGuid>39451654-572d-4263-a3b5-29f51511f63b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
