<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MesEneroFebreroMarzoAbrilMayoJunioJu_5634e8</name>
   <tag></tag>
   <elementGuidId>93429541-1f04-44d4-9ff4-3920c8bacdb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ComboMes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ComboMes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e05869da-879c-4382-a3fb-65ee525f7bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LabelNegro  ComboInfragistic Flecha</value>
      <webElementGuid>048aa0cf-536d-4ba4-b523-90a39d23b119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ComboMes</value>
      <webElementGuid>d038da0d-ddbf-453d-af66-c836d8ee7128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mes</value>
      <webElementGuid>d1688f1d-035f-4d68-8b4c-b679a4712a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>63f26a03-257f-4aad-8ac5-bdbb46d8a59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mes
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre
</value>
      <webElementGuid>082c5726-1f1f-41bf-ae5d-63ad9a5bdcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ComboMes&quot;)</value>
      <webElementGuid>a510b833-b633-4361-8652-a4164de7a3df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ComboMes']</value>
      <webElementGuid>0020e34e-87a9-4f35-b358-c5e2c0365f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmMicroCreditoInternet']/div[3]/div[5]/div/div[3]/div/select[2]</value>
      <webElementGuid>4328fed9-08c5-49e6-a2e7-878c9463e50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[2]</value>
      <webElementGuid>6e76e75f-d49e-4d65-8764-1532469766c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO es una fecha válida'])[1]/preceding::select[2]</value>
      <webElementGuid>c4785894-5bf6-44db-b224-f46fa58a4bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa correctamente tu fecha de nacimiento.'])[1]/preceding::select[2]</value>
      <webElementGuid>56b8e08b-cfcd-4dba-bbdb-e1a2669939ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>5ac034ec-bc1c-45df-a872-2ad5e0040fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ComboMes' and @name = 'Mes' and (text() = 'Mes
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre
' or . = 'Mes
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre
')]</value>
      <webElementGuid>bffa18a5-04cb-4510-9ae3-971049568276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
