<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oficina_btn btn-primary</name>
   <tag></tag>
   <elementGuidId>49545ca8-854f-4182-b1b9-a75f7c56f986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Ingresar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd174803-b53d-4780-b2a4-1910b0e33918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e32cd107-ddcc-4156-98e5-8fa02c861785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Autenticar();</value>
      <webElementGuid>c2776db2-6c89-4f24-812c-c815052e237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>1d36afba-5462-4847-b096-413b3abaaf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4d15ae08-3999-41f3-aecb-8d4c652c958a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-3 col-md-5 col-md-offset-4 col-lg-4 col-lg-offset-4&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12 controls text-center&quot;]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>d0ac7e09-86d6-499a-993f-9b02b21e2c40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Ingresar']</value>
      <webElementGuid>adc5015c-4cb1-4fca-a337-ed2fb6db857f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section2']/div/div/div/div[3]/div/input</value>
      <webElementGuid>f4737133-ab6f-4c2b-8233-3e2ed18603fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>30babc2f-41cd-4998-a564-528daa81b3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>0eeae28f-61d4-418d-b1bf-244284289371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
