<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Campaa</name>
   <tag></tag>
   <elementGuidId>8c7cc34f-a62a-46f7-bef3-c73ec042af16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPresentarOfertasBotonConfirmacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3d3f0ce-e29d-41b8-b074-718e8402b73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2215365-31ef-4d77-8f03-859c223fc307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPresentarOfertasBotonConfirmacion</value>
      <webElementGuid>0904e9af-a96d-4f60-a260-c942e888ac88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>96ff9659-ed77-4f30-86ad-8cd340fe0d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b3c3f56-329f-4d14-8e14-96a49eac6561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Campaña</value>
      <webElementGuid>07a0527d-f669-40a2-934d-b840e596ab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPresentarOfertasBotonConfirmacion&quot;)</value>
      <webElementGuid>13803dde-b790-4deb-8776-a051d401a0c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      <webElementGuid>a590661d-522f-4509-8fc4-2c218eb29ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      <webElementGuid>1352a782-127b-4bb3-8f61-5c76772598a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>65807247-b029-46aa-b566-f93f1abdd069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$700.00'])[1]/following::button[2]</value>
      <webElementGuid>0f06b23d-511b-4407-97ac-da60607e7add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Generadas'])[1]/preceding::button[2]</value>
      <webElementGuid>29dea1d8-0c77-4a0c-b842-7a1bbbf5bdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Generación'])[1]/preceding::button[2]</value>
      <webElementGuid>fd006b14-fe5a-4301-85bb-3ca45e3b99f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Campaña']/parent::*</value>
      <webElementGuid>be6d57ff-db11-46ff-a870-cb0473d36033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button[2]</value>
      <webElementGuid>73656af0-ac8d-46ec-b0a0-b01191305043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'modalPresentarOfertasBotonConfirmacion' and (text() = 'Generar Campaña' or . = 'Generar Campaña')]</value>
      <webElementGuid>4a7d888c-6df6-4884-bb86-cfe9e02815c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
