<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar</name>
   <tag></tag>
   <elementGuidId>102c0b3d-cc36-42f9-bf49-664435b7c3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonBuscarCliente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonBuscarCliente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d691851-a530-4c30-8542-45248039aa93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba0751f1-5a5b-4e32-8aa9-05c34a2d7038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonBuscarCliente</value>
      <webElementGuid>3bba2be7-a921-4626-8afc-ab0033c61bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e5eb1f0b-1adb-4f8c-b7ec-6ba208efddba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d7095dc-1ad7-400f-8fff-74056e15c88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>63b04771-471d-4653-8ab9-e57035393725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonBuscarCliente&quot;)</value>
      <webElementGuid>220a0d18-7bbd-430d-9884-2bbd7bab7cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonBuscarCliente']</value>
      <webElementGuid>89b2ff88-7d33-447a-b622-f1f24933e333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div[2]/button</value>
      <webElementGuid>0f5939de-bf23-4ae3-871c-76f15d069f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identificación:'])[1]/following::button[1]</value>
      <webElementGuid>96c07914-0c77-4e7a-a6d0-7f8bfd3b6999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Cliente'])[1]/following::button[1]</value>
      <webElementGuid>a2dcfe22-a501-4231-b228-f0bd105fb93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/preceding::button[1]</value>
      <webElementGuid>93d45e6b-a8ea-4025-899c-ee15dbf5da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reimprimir Oferta'])[1]/preceding::button[2]</value>
      <webElementGuid>c3bbf1d4-a8e6-4169-9d77-e767028f15fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>4ea1fbb3-542f-40ac-bc08-274162f3aac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e68145e6-380e-48d4-845d-1dce78bc0668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonBuscarCliente' and (text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>a9ce8359-0b8d-4ca0-8b77-de678dc11ab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
