<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>3315c05e-4790-48eb-8b3a-719d3221edc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalDocumentoGeneradoCerrar > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalDocumentoGeneradoCerrar']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fedac6d-9ee6-4cab-9174-f45268d8c591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b2b7031-3987-4b6b-a4b9-be749718432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>0bc89c7a-88a7-4dd9-a262-9175ea78446d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDocumentoGeneradoCerrar&quot;)/span[1]</value>
      <webElementGuid>5af74089-c1ec-4b4d-a192-94e778c894a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='modalDocumentoGeneradoCerrar']/span</value>
      <webElementGuid>01497972-c405-4bfa-a5bf-3734450ef649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oferta'])[1]/following::span[1]</value>
      <webElementGuid>e07c7e1a-6475-40d9-9796-cb82645d4c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secuencial'])[1]/following::span[1]</value>
      <webElementGuid>37ff3220-d1b0-47be-8b40-e6e655e54bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documento'])[1]/preceding::span[1]</value>
      <webElementGuid>ce6227e2-0145-45c4-92df-eeabb5e4d692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Internos'])[1]/preceding::span[2]</value>
      <webElementGuid>4799c943-ee7d-4ceb-b671-ac65ae12b8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button/span</value>
      <webElementGuid>da2dba8e-7682-4402-8066-fddbaea5a9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>0783c5f9-cd8e-439f-84fa-4597b0c12c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
