<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>108a1922-c370-445f-a9da-0020a25b6ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.labelGLNegroMensaje.text-center > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='CerrarDialogoCardMail();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aef6b583-8a7d-4ffc-a599-c9a62a46ffd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/boton-aceptar.png</value>
      <webElementGuid>436e7212-bea7-4724-b04c-8906ef3a3197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CerrarDialogoCardMail();</value>
      <webElementGuid>94d9408f-9f3e-4f13-b9a2-fbe2b3dfbede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecomendacionNavegadorMail&quot;)/div[@class=&quot;dialog-cardMail&quot;]/div[1]/div[@class=&quot;col-md-12 col-xs-12 text-center&quot;]/p[@class=&quot;labelGLNegroMensaje text-center&quot;]/img[1]</value>
      <webElementGuid>9a9fd6e8-4553-41f7-b2c8-9c455f3bbba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='CerrarDialogoCardMail();']</value>
      <webElementGuid>93eca1db-ca18-4a9f-9f32-7a663ca6d58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RecomendacionNavegadorMail']/div/div/div/p/img</value>
      <webElementGuid>294796d9-0f43-4550-9b43-0e08c2332918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
      <webElementGuid>e463bc7b-d2ad-40eb-9450-44b994ff7dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/boton-aceptar.png']</value>
      <webElementGuid>8f9031c2-024d-426a-aeb6-1729371b57d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
