<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No es una fecha vlida_TelefonoCelular</name>
   <tag></tag>
   <elementGuidId>cc1b9819-17d4-4f3d-818a-863ff33d8abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TelefonoCelular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TelefonoCelular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71bcbb3f-0e13-4835-bfe8-84a2ae4e3275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fbdfeb90-bd3e-4dd9-9438-d7f0bc405213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e62a924-9844-4696-853c-001ba6a976f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TelefonoCelular field is required.</value>
      <webElementGuid>c8f5c927-147c-43eb-82d3-6d5118a2a0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TelefonoCelular</value>
      <webElementGuid>49654374-95b3-4c82-a8ab-8e876ca6d0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TelefonoCelular</value>
      <webElementGuid>dfa28441-d6d2-4587-8809-848fe3eeec86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return Validarnumerocelular()</value>
      <webElementGuid>4aa6ec22-1ffb-4e61-b9ef-d0114e125d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Teléfono celular</value>
      <webElementGuid>4ab8dca6-f68a-4921-b7fd-fe7f9b42b4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bf423c42-8d29-43b1-a668-9f63f174fb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bc862d65-401c-4cea-9ce8-c458366d204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>36bc9db5-7652-4184-8a88-61c2aba37831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TelefonoCelular&quot;)</value>
      <webElementGuid>a50c2498-a4f4-44c0-8b02-e8453850453b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TelefonoCelular']</value>
      <webElementGuid>faaa5eac-ff48-45bd-b0b2-fd80c57458d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div[2]/div/input</value>
      <webElementGuid>d7761934-6f46-4d0d-9776-89bd4e058f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>10eab8db-f88d-4de7-be54-e2357e76594f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TelefonoCelular' and @name = 'TelefonoCelular' and @placeholder = 'Teléfono celular' and @type = 'tel']</value>
      <webElementGuid>4616be7f-b3ce-45ee-9611-d039038c6a74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
