<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vamos a empezar, ingresa los siguient_c53a2e</name>
   <tag></tag>
   <elementGuidId>1298f67c-fc65-4df8-a86e-7ea4e936b3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Identificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5c76829-7d6f-479e-a21d-0c28f92154ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>016953cb-7c5c-4c39-8b0f-b59caa236556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37f359c5-c45a-4eb6-87dd-c671628a5ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Identificacion field is required.</value>
      <webElementGuid>2293f52c-1ec6-40ad-8d6f-cabc3984e188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identificacion</value>
      <webElementGuid>c8c9be06-a2d4-4393-bb18-165e61c1aac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>09e42766-1303-440d-9ea1-95725a142ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Identificacion</value>
      <webElementGuid>ccc0ced9-d865-47ab-bb84-49f6e6786b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>ef9747f0-4900-4834-9ca5-37add5d2fdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return numericOnly(this,event)</value>
      <webElementGuid>bdf1a953-1b08-402a-8a8b-9a1e94dcf171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cédula</value>
      <webElementGuid>fdbf5cba-f421-4cde-8ebb-c3c2521b55a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>81a5f243-d220-437f-adbf-bf1abe462648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a872581d-e0a8-4ba5-9797-216e2803dad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identificacion&quot;)</value>
      <webElementGuid>63165231-a515-4b2a-a8d3-1fc462a3cd35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identificacion']</value>
      <webElementGuid>24bfd45a-b528-43ea-b7de-e4bbfc719723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[5]/div[3]/input</value>
      <webElementGuid>afcdf1c5-cb17-46ad-a626-cea536aca9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>98a65a2c-3509-44fa-8e84-7659044ff4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identificacion' and @name = 'Identificacion' and @placeholder = 'Cédula' and @type = 'text']</value>
      <webElementGuid>c58230e2-4588-4033-b93d-0b3a0fc2ae3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
