<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Nacimiento no pertenece al cedu_1a96b4</name>
   <tag></tag>
   <elementGuidId>7e88ecc1-c78d-4bfe-9793-1aa057b0291e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FechaNacimiento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FechaNacimiento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea48a5f9-bf9d-4821-9719-54a84b625b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e7038c13-3d5b-4dd7-a8c3-68ae9608f481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a76ff53-f9e7-4e7c-a884-600c6fc8bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Salud must be a date.</value>
      <webElementGuid>4db8d801-f488-46ce-a354-079d38418324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Fecha de Nacimiento es obligatorio</value>
      <webElementGuid>43cae4ac-4ab2-4942-8b04-53b3b45f498c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>95bf5a0f-451f-45fb-80c7-605e960f853f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>23c858f1-5226-460a-8af2-323398bde448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>19b5ba06-1ae9-42a9-8fd6-9945d2e0ecef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fecha de nacimiento dd/mm/aaaa</value>
      <webElementGuid>27a2f2d1-4f59-46d3-8f95-ea97cb950dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9eec2584-fffd-45b0-a0a8-6db14f478c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/01/0001 12:00:00 a. m.</value>
      <webElementGuid>84fc4dd2-1544-4049-aa1b-6c9dc2f1712f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e5db7ea5-274c-44a2-83d8-04b178b4b484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FechaNacimiento&quot;)</value>
      <webElementGuid>e7e35d6f-7312-4e11-8d67-b74489514652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FechaNacimiento']</value>
      <webElementGuid>222b0acb-2fb1-4d93-8b7f-00a5801f970a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div/input</value>
      <webElementGuid>e5b6cc25-936c-47df-b4dc-fcf378c941e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>102a97f8-577e-44f0-9131-5eece9f6cc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FechaNacimiento' and @name = 'FechaNacimiento' and @placeholder = 'Fecha de nacimiento dd/mm/aaaa' and @type = 'text']</value>
      <webElementGuid>1dfc7952-52eb-4d33-be9a-f84337f6bf34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
