<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No es una fecha vlida_CorreoElectronico</name>
   <tag></tag>
   <elementGuidId>1c8eb9ff-452f-460a-8dad-8e37fa54a683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CorreoElectronico</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CorreoElectronico']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca31e7a3-c541-409c-9707-1eb87b45bb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3386b5a-cb0a-4bb2-b8d9-c20ae377873a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d79fbf53-d069-4c28-a0d5-dcc5283b7f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CorreoElectronico field is required.</value>
      <webElementGuid>743154ec-9355-41d2-8865-2aa85308f33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CorreoElectronico</value>
      <webElementGuid>d85d7605-ceea-4297-a546-0d8579fcb9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CorreoElectronico</value>
      <webElementGuid>588c7200-8a28-443e-b033-cd090e8292a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{1,5}</value>
      <webElementGuid>79b82eb1-e2c5-4ccb-9bec-4875ec9a938d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Correo electrónico</value>
      <webElementGuid>d54983c3-e7c5-41fb-b927-6974d3586d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>2b014a67-e1df-4d15-8268-f9df1ee3bbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>729290f3-1682-4511-92e6-9b9f328c5c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CorreoElectronico&quot;)</value>
      <webElementGuid>e581d398-b7cd-4320-bd82-9f5ceaa59f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CorreoElectronico']</value>
      <webElementGuid>d410f9b9-f0b2-4b24-8d06-dc2bfc716983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div[3]/input</value>
      <webElementGuid>49dfe548-c6d5-432f-8877-9f9e84c0c036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/input</value>
      <webElementGuid>c96f6298-edfd-4bab-934b-a65d2ad8a7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CorreoElectronico' and @name = 'CorreoElectronico' and @placeholder = 'Correo electrónico' and @type = 'email']</value>
      <webElementGuid>d69248d7-6e2a-4d20-9652-abf009cddef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
