<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El Correo no es vlido_Autorizacion</name>
   <tag></tag>
   <elementGuidId>e80defc2-5137-4b44-8154-05273ce3c6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Autorizacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Autorizacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f50fd64-dfcc-4cb5-a846-75acbc874e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c053d18c-4063-422e-a7e5-42aff8ac9fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Autorizacion field is required.</value>
      <webElementGuid>2d385d72-8c1d-46bf-8679-9c477419607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>c8aba1de-0b76-4983-b05f-18f47f283baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>98e7e2c6-6fb8-4108-9227-660456a7954a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.setCustomValidity(validity.valueMissing ? 'Por favor autorizar que sus datos sean consultados' : '');</value>
      <webElementGuid>24e376fc-bc76-4749-94f4-f00b11904918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>52d5cd3e-7dff-471a-8201-32a0000d9fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11c66083-f7c0-4c96-86aa-c635c924fee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5bd24828-2dc1-4bca-b0f6-6a38221f0825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Autorizacion&quot;)</value>
      <webElementGuid>7527b0f8-01bd-418c-a122-961204509ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Autorizacion']</value>
      <webElementGuid>c5b096ba-6d37-4c42-b1f9-fb2fafb67aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[8]/div/div/input</value>
      <webElementGuid>86fd9ff2-a319-4ab0-ac4d-5929fd9102c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>3fa644ed-df67-4879-8df3-7c267f5fcb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Autorizacion' and @name = 'Autorizacion' and @type = 'checkbox']</value>
      <webElementGuid>3fd572ed-708e-495a-903c-a5a2cbfeca48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
