<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vamos a empezar, ingresa los siguient_6b91ac</name>
   <tag></tag>
   <elementGuidId>d61dac97-9cc0-44dd-a63a-7e5e813a1fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PrimerNombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PrimerNombre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34106a32-7f84-47ad-9969-b00301a4c881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>25b88416-b3fd-43c7-8de5-7ac9c81dd0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3247d3ed-9396-49f0-8763-eaabf527d8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PrimerNombre field is required.</value>
      <webElementGuid>dc416f7f-5cae-49fa-96a4-17cc9f685c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrimerNombre</value>
      <webElementGuid>d44ceac3-8cc8-4b58-8a0c-9c63f158fd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimerNombre</value>
      <webElementGuid>a33835dc-891a-4a84-b953-533a2e9976fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre</value>
      <webElementGuid>7ccf6232-0b45-4274-bd66-ec2d05ba6918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>060d63f8-468c-48a1-adeb-1db236d4fecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12c2b60a-2fe8-4eef-8393-a7a2ce4dfad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrimerNombre&quot;)</value>
      <webElementGuid>2dc58d6f-6d70-43b4-afa3-6b050eb5fc47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PrimerNombre']</value>
      <webElementGuid>b886aea4-e65a-486d-83d3-9957b04fd62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[5]/div/input</value>
      <webElementGuid>d071a42f-b4ec-47c2-bde4-683d883fe35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>813fd487-e460-48fc-a152-b228ba0dc8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PrimerNombre' and @name = 'PrimerNombre' and @placeholder = 'Nombre' and @type = 'text']</value>
      <webElementGuid>f5c66223-5640-422f-8031-49a70b02bbf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
