<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calle Transversal_CalleTransversal</name>
   <tag></tag>
   <elementGuidId>4366b6df-5790-4bbf-8f73-bd160707e3b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CalleTransversal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CalleTransversal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f5bdb6a-f8f5-42ae-906b-3c732444fbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control labelGLNegro labelTamanio</value>
      <webElementGuid>ed95f4bc-57b6-4614-8b9c-1e091271f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44160b5e-d610-4114-8d93-54b6fc1901dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CalleTransversal field is required.</value>
      <webElementGuid>905858e8-0c73-4546-80bb-0b77d32f7080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CalleTransversal</value>
      <webElementGuid>aa540c57-6adc-4da1-9eb6-d3873bff6f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CalleTransversal</value>
      <webElementGuid>4f874b2f-7a37-4713-a9f1-c2c906eec0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>a3f547c0-3481-4711-872d-762425d5e639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Ingrese la Calle Transversal de la Empresa.')</value>
      <webElementGuid>8767244f-5104-41ce-a07f-3562cd493fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>88064b07-abe7-41a2-a209-dc44041ed237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b195da5-d684-470c-84d6-ec5b502900ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CalleTransversal&quot;)</value>
      <webElementGuid>236d1d07-f724-4b00-a3ba-10ca6e502b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/SinPopUp_SinInformacionLaboral/Page_Solicitar crdito/iframe</value>
      <webElementGuid>9107b6e2-7b29-470b-8de2-8101380b5164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CalleTransversal']</value>
      <webElementGuid>9023983c-d5ac-46d6-99ff-cbb6b81743f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div/div[4]/div/div[4]/div[3]/div[2]/input</value>
      <webElementGuid>4e287db4-5393-4946-96ac-ab947fd29935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>456b51ca-cc47-4721-8019-db4831d217de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CalleTransversal' and @name = 'CalleTransversal' and @type = 'text']</value>
      <webElementGuid>17751f66-044f-4155-95ff-7ad22f868459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
