<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GasAlimentacion</name>
   <tag></tag>
   <elementGuidId>097c931b-6df8-4b07-9e95-81886d6595c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasAlimentacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasAlimentacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83afe50f-03fe-4e63-9228-a820960d886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>5a4e461a-3b45-4bcb-ab5d-ecc3fdfc0eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmtallocated pull-right</value>
      <webElementGuid>6d20fa8d-dea9-4901-9065-c7c3a424cc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>27e6ad71-a1bb-446f-9897-6cbbed6cac97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field GasAlimentacion must be a number.</value>
      <webElementGuid>fa62ff20-ee04-4f11-be1c-27ebb7324c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GasAlimentacion field is required.</value>
      <webElementGuid>c840daa2-c95b-4fa8-9ffd-28f927827131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasAlimentacion</value>
      <webElementGuid>643f2895-5f07-4d2d-961f-ac331b6d34c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasAlimentacion</value>
      <webElementGuid>f783bee4-b498-4b52-8d2d-d0bd7efd279f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calcularGas();</value>
      <webElementGuid>3b7daaa3-ee2b-433b-888d-3f79785b6578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('GasAlimentacion')</value>
      <webElementGuid>db73969c-a080-4bae-b706-00d6366c8ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>2b1d9ce3-d9e3-402b-bdf8-7e0f5654c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'GasAlimentacion');</value>
      <webElementGuid>bf9ed6ff-0909-41a5-bde5-05ef3a747990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bac7144e-ed64-43b9-83a6-baf6ef803400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf63aba4-604b-4584-8ff2-ecc3fdfe8fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasAlimentacion&quot;)</value>
      <webElementGuid>96db073f-321e-4374-8b24-bb690422672e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/SinPopUp_SinInformacionLaboral/Page_Solicitar crdito/iframe</value>
      <webElementGuid>ba4d99f9-0140-4199-914a-3f99bb1f8c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasAlimentacion']</value>
      <webElementGuid>e97bb0eb-9be8-45bd-bba6-8cc31b50c5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div[2]/div[5]/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a0aaa3e9-4e3c-4839-8e5d-106d7f2ea46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6f0a4f24-2440-4127-a91c-3526f860f152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasAlimentacion' and @name = 'GasAlimentacion' and @type = 'text']</value>
      <webElementGuid>049dca7f-86eb-497e-884d-4a6a0192bf45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
