<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GasServiciobasico</name>
   <tag></tag>
   <elementGuidId>73a67639-c58b-4fd3-82a7-1589a05fa267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasServiciobasico']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasServiciobasico</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e314756-871d-4d7c-a5a5-1e49373d3bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>da9596f7-21e0-4e95-a12c-e09feb250dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmtallocated pull-right</value>
      <webElementGuid>bf716dd3-353a-4b44-abaf-c8223b2e8b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a79a7b1-1107-4fba-9305-712187703f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field GasServiciobasico must be a number.</value>
      <webElementGuid>25c77fbf-9b5c-451a-a689-b9b0805dbd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GasServiciobasico field is required.</value>
      <webElementGuid>28716b8c-2710-4348-8e97-20c2ce71ea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasServiciobasico</value>
      <webElementGuid>8a48e337-15d3-4f72-b394-ba044a87c4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasServiciobasico</value>
      <webElementGuid>d864121a-04c9-4403-ae0b-9c77b82077fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calcularGas();</value>
      <webElementGuid>55ff88c9-8447-4581-8539-71f7d3bbac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('GasServiciobasico')</value>
      <webElementGuid>712f134f-cdc1-44c5-af47-3c28f3c41f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>34d42383-66bb-4c72-9cfd-734e56bdccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'GasServiciobasico');</value>
      <webElementGuid>0748da36-70e8-4faa-a493-f73ce9270752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62b3768b-a4b0-4ed4-9026-8fa90df0a94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5446f27f-dda5-4cd9-96c7-424608cdb1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasServiciobasico&quot;)</value>
      <webElementGuid>f00e6a25-1bf9-4cdd-9f54-b3370c487477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/SinPopUp_SinInformacionLaboral/Page_Solicitar crdito/iframe</value>
      <webElementGuid>11bcf0dd-bf7b-42c0-acde-bc155644cc81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasServiciobasico']</value>
      <webElementGuid>e69f72fc-b313-4874-8b6a-a7b65567f9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div[2]/div[5]/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e0946cf0-07ad-4a3b-99fc-e34b5cbe141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>97b4d9cf-c416-4b69-b9a8-5ff27a247572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasServiciobasico' and @name = 'GasServiciobasico' and @type = 'text']</value>
      <webElementGuid>ac638d7a-0a04-460c-899d-ef6a81dc1e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
