<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ActSalariosueldo</name>
   <tag></tag>
   <elementGuidId>6a006c20-8c13-46f1-b3db-b428964da325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActSalariosueldo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ActSalariosueldo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7854f3a4-e494-4b6d-b9f1-c247e7288a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>f9af4ba5-f794-4770-9b60-c83ee798d291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmtallocated pull-right</value>
      <webElementGuid>4103c026-d50d-4e19-be27-bb7f30e0b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdc8c7bb-c63f-4c8c-ac18-68473bc04fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field ActSalariosueldo must be a number.</value>
      <webElementGuid>68b69ed1-5a55-431d-90ba-3297cc0b818b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ActSalariosueldo field is required.</value>
      <webElementGuid>51eefd27-2430-4a97-b6f5-b1edb87dab8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActSalariosueldo</value>
      <webElementGuid>b32a4fd7-2a29-4239-96a7-4a6ef265adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActSalariosueldo</value>
      <webElementGuid>634c37ed-5433-498d-bd1b-3f542cc4fe4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calcularAct();</value>
      <webElementGuid>98a69cf4-42c0-4ba7-a064-61ea9feedc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('ActSalariosueldo')</value>
      <webElementGuid>23bf6cca-e8af-483f-b27f-b3940229c138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>4665a15b-ae1a-454e-b789-894538781e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'ActSalariosueldo');</value>
      <webElementGuid>9b7377be-0628-4622-a3ac-0fcf03689d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d72c5be6-1786-46fa-8b51-df574aed4e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c6555cc-5cf5-4afd-b24b-e5261d39e077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActSalariosueldo&quot;)</value>
      <webElementGuid>897bd356-a914-457d-aff8-e3eee08b1b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/SinPopUp_SinInformacionLaboral/Page_Solicitar crdito/iframe</value>
      <webElementGuid>36b7be30-ea8d-45a3-9a54-cc2db92d5fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActSalariosueldo']</value>
      <webElementGuid>cbf59f6c-f955-47dc-b704-b92fef5856c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div/div[5]/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5b22156b-bb94-4eac-bbb5-0d97cda7b736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>3e5084b7-971f-4384-82af-4ebda8945da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ActSalariosueldo' and @name = 'ActSalariosueldo' and @type = 'text']</value>
      <webElementGuid>c490d5cb-7cf6-4836-913d-baf7dab6d38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
