<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione ParroquiaALANGASAMAGUAAAT_dc6fce</name>
   <tag></tag>
   <elementGuidId>68445d4c-4af0-436e-ae97-143e32df302a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UbicacionGeografica3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UbicacionGeografica3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0d203b5-e123-469c-ba6b-22bcd406416c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control labelGLNegro labelTamanio2 DropDownListsolidario</value>
      <webElementGuid>a75597e4-fd5b-43b6-97a2-0dea56e22c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28d38ac9-b91b-409a-a223-4e27cfc8404c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The UbicacionGeografica3 field is required.</value>
      <webElementGuid>f4360eec-7953-4a35-87f5-f29b3a3b10ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UbicacionGeografica3</value>
      <webElementGuid>907c76f4-3cde-4a19-b735-47aa0f5e3175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UbicacionGeografica3</value>
      <webElementGuid>327b6b67-a44c-4b19-aadb-dd552c10be9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ObtieneBarrios();</value>
      <webElementGuid>f01b0413-2607-4e1c-a304-5563c438d526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>ec5ba49b-b507-4ccf-b4f6-5df5f6822eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Seleccione la Parroquia')</value>
      <webElementGuid>a1a48665-c8f3-41fb-b12c-7fa41703a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>Clear1();</value>
      <webElementGuid>33f03636-16dc-46a8-befa-14b567383c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4a70e31a-1960-4ee2-ab0e-752c1e302272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA</value>
      <webElementGuid>a448b7f3-e31a-41a0-8c65-ab4bea1028d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UbicacionGeografica3&quot;)</value>
      <webElementGuid>85c4aec5-5f00-4e36-8766-05fe5e0ec18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/SinPopUp_SinInformacionLaboral/Page_Solicitar crdito/iframe</value>
      <webElementGuid>d3862e47-cede-4b9e-9ec9-406759b3aaaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UbicacionGeografica3']</value>
      <webElementGuid>31ac7208-bb0c-4e7b-95f9-1659d8d35163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div/div[4]/div/div[3]/div[3]/div[2]/select</value>
      <webElementGuid>613b3692-90d7-4f94-a440-a9d0d965c304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parroquia'])[1]/following::select[1]</value>
      <webElementGuid>40c6b4ea-0f4f-4369-a268-d0fd2c9fa40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>fd469fa8-12ae-475b-b5ac-0a26e7d45f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barrio'])[1]/preceding::select[1]</value>
      <webElementGuid>39fb0790-eff5-4bb3-b74c-0f83569e06e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[2]</value>
      <webElementGuid>0c2ee8fb-2c0b-4031-b9e7-9e0f7c725b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>02e50b55-da27-4eaa-b800-1fe68d9a473f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UbicacionGeografica3' and @name = 'UbicacionGeografica3' and (text() = 'Seleccione ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA' or . = 'Seleccione ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA')]</value>
      <webElementGuid>0639f328-6222-409f-8c07-95fdacd520dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
