<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>5c76d3cb-3f6a-4179-b4cd-de64d3521768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//use[@href = 'assets/factoricons/symbols/factoricons-regular.svg#angle-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>use</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>8f8a663c-ec4c-4b5c-ab72-33cf5513fe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>assets/factoricons/symbols/factoricons-regular.svg#angle-right</value>
      <webElementGuid>5f86ac1c-cb49-4785-afd5-7d2873de419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>assets/factoricons/symbols/factoricons-regular.svg#angle-right</value>
      <webElementGuid>0480ff9f-6659-4d8c-a32a-c4fa1c5880d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/app-renew-credits[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/mat-card[@class=&quot;carousel mat-card py-4 mb-4&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/button[@class=&quot;carousel__btn mr-n4 mr-sm-0 mat-button mat-button-base mat-primary ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/ft-icon[1]/svg[1]/use[1]</value>
      <webElementGuid>f2e9d84e-7d21-479b-bedf-e08229d01a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//use[@href = 'assets/factoricons/symbols/factoricons-regular.svg#angle-right']</value>
      <webElementGuid>b5f72966-2f80-4655-a828-f869b468542e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
