<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LO ENTIENDO</name>
   <tag></tag>
   <elementGuidId>5481924b-8815-422d-ac1e-a3fa0c53bb29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-footer.text-center > button.btn.btn-Solidario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3e02caf-81ad-4fe2-9e63-58da0dcfd9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>becf539a-e70b-411d-b7fc-085758121a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Solidario</value>
      <webElementGuid>1ea5bd60-850a-4926-88ef-fb1e65a72c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>08fd9927-2d33-4016-a19b-6d219207683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LO ENTIENDO</value>
      <webElementGuid>3b359a7c-7a55-40b9-8d49-2ca310c0aa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalNotificacion&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content dialog-info&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;card-footer text-center&quot;]/button[@class=&quot;btn btn-Solidario&quot;]</value>
      <webElementGuid>c2646282-4dba-4030-acf1-2a6fa0448a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>27b23006-accd-4d8e-9ecb-5241aeb1d548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNotificacion']/div/div/div/div[4]/button</value>
      <webElementGuid>19d39a07-9abd-4748-87e0-68942c9173ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TU DOCUMENTO SE CARGÓ EXITOSAMENTE'])[1]/following::button[1]</value>
      <webElementGuid>793b4527-29c1-4e57-a749-c7c7b7890176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERRAR'])[1]/following::button[1]</value>
      <webElementGuid>990a8446-f92a-44da-bbf7-147c6c3ded9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿ESTÁS SEGURO DE SALIR Y NO OBTENER TU CRÉDITO?'])[1]/preceding::button[1]</value>
      <webElementGuid>6fca2dc2-05d0-4687-ba44-696751e51c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI DESEO SALIR'])[1]/preceding::button[1]</value>
      <webElementGuid>99b50eab-0588-403c-b0f2-592adf4ec00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LO ENTIENDO']/parent::*</value>
      <webElementGuid>a329a608-bce5-4eb1-87f8-ecea4c9f4b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>181e1369-d587-4401-b328-f85105bfaa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'LO ENTIENDO' or . = 'LO ENTIENDO')]</value>
      <webElementGuid>44564e9c-3c74-45e7-86f7-abf26e31f75a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
