<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TABLA DE AMORTIZACIN_img-check</name>
   <tag></tag>
   <elementGuidId>86ee6671-ff38-4cac-b3fa-d16efcc32f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img-check']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img-check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>429bd59e-6132-4ae1-9c49-58e499a686f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img-check</value>
      <webElementGuid>a973c71f-5709-46e6-bb53-d02efcae6d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CreditoNoCliente/solidario/img/down.png</value>
      <webElementGuid>b1aaaf57-6e9c-4046-9dad-9f27e0a8fbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-check&quot;)</value>
      <webElementGuid>f3f64566-2dc8-49fd-8dce-65fea5934d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img-check']</value>
      <webElementGuid>1b4fa7f1-5097-4908-beb2-219c3f54116c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CabeceraTablaAmortizacion']/img</value>
      <webElementGuid>61a392ca-d826-4699-b9e6-33ece124409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/img</value>
      <webElementGuid>f1fb1c16-e2e7-4551-bb48-d16a32b77005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img-check' and @src = '/CreditoNoCliente/solidario/img/down.png']</value>
      <webElementGuid>9e3d9470-f6ce-4b7d-9b56-1b7f1ef13ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
