<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tus gastos mensuales_GasSalud</name>
   <tag></tag>
   <elementGuidId>3b9e3757-8564-4b0a-9f6e-2a7269b802eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasSalud']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasSalud</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91117dd3-a69b-47dc-b859-4188072f2f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6d654196-1e09-4929-aca3-893b19f47762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>073327cc-8eb9-40c8-8363-63675159332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Salud must be a number.</value>
      <webElementGuid>62bc8045-b3eb-4c45-954e-43155923939e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Salud field is required.</value>
      <webElementGuid>b643d43c-48b2-47ec-a5da-e76e50988a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasSalud</value>
      <webElementGuid>928b766e-151a-4945-9860-0b1652d0413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>eaeb62f0-a426-42ea-95c6-25bb2ad7740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasSalud</value>
      <webElementGuid>970ef63c-0d5d-4f37-a4b4-bdb619212a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return filterFloat(event,this);</value>
      <webElementGuid>e7e50391-9e75-4337-a18e-5d6f4b1ad3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$ Salud</value>
      <webElementGuid>ad8f53d2-d088-4421-81e8-c7c5cd02d4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79f448c3-8966-4fbe-94a9-a92a65796220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasSalud&quot;)</value>
      <webElementGuid>bfc7b347-68b1-4408-a8ed-bebcb439b356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasSalud']</value>
      <webElementGuid>72d34612-29a5-4855-87d1-c293c67e755d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosFinancieros']/div/div/div/div/div/fieldset/div/div[9]/div[3]/div/input</value>
      <webElementGuid>97331f20-7022-40cd-aaf2-c2cfabbb572c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/input</value>
      <webElementGuid>cf675413-2154-4d54-aa2f-f5917c6747a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasSalud' and @name = 'GasSalud' and @placeholder = '$ Salud' and @type = 'text']</value>
      <webElementGuid>a72a3acb-9db7-4435-b47c-98f025c0fc7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
