<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Datos de tu domicilio_DatosDomicilio._270291</name>
   <tag></tag>
   <elementGuidId>2e4a7586-94d4-4373-8357-1760c3e2557c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatosDomicilio_CalleTransversal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosDomicilio_CalleTransversal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e265f96a-1b7f-45af-88f4-dd1e2b8f43d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7627a798-89ab-4974-8abb-d7215e1f9143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29b21339-8f6a-4615-9be4-a46bc65c9347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 64 caracteres</value>
      <webElementGuid>f8ce3360-cfdd-4c00-90a3-4f8163f40eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>d9758ab5-3aa4-4354-811a-ddaecd1e3d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Calle transversal es requerido</value>
      <webElementGuid>3f57b6e7-4d77-4b29-b87d-57a0ec15e7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosDomicilio_CalleTransversal</value>
      <webElementGuid>8ec3fdfb-1ef7-4456-b7de-cb6133f2afb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>cbb14538-54aa-412b-8db1-97df5f8468b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosDomicilio.CalleTransversal</value>
      <webElementGuid>52f74680-bd2a-4c36-bc17-9040b2f8f3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Calle transversal</value>
      <webElementGuid>c5dcb4b6-075a-4143-bcdc-d14e0bfca86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>995f1931-ac82-4e4b-a957-78258d8ecd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b468b1d3-d224-4daa-94e4-918bda7ed2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosDomicilio_CalleTransversal&quot;)</value>
      <webElementGuid>a5a6fe99-4972-4469-9e09-b7db67174f59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatosDomicilio_CalleTransversal']</value>
      <webElementGuid>ca0a11f0-b03b-4a16-8ed8-02ee6c67a667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[4]/div/div/input</value>
      <webElementGuid>da381189-04d7-40c9-856a-a29bbc65ffa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>e3d2919e-c526-43c4-b98f-7ba904cadf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DatosDomicilio_CalleTransversal' and @name = 'DatosDomicilio.CalleTransversal' and @placeholder = 'Calle transversal' and @type = 'text']</value>
      <webElementGuid>2a3363b1-dc58-4cc0-8da2-65c65cc5c774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
