<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referencia Personal_ReferenciaPersona_ebf4ce</name>
   <tag></tag>
   <elementGuidId>079b9cf1-deac-4d1c-a1ae-f752b7ca89d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReferenciaPersonal_PrimerNombre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReferenciaPersonal_PrimerNombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ef6caa7-7fb0-430c-9ec2-3c49128296c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b54ad37f-8b97-46b0-b9d4-cfff6605ff3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1269ef80-9c77-4108-828a-1cddbc1fceb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 32 caracteres</value>
      <webElementGuid>952c02ed-c98a-4c07-b08b-7a2218e7777a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>ca9b7bba-9f6d-43ab-a0fd-f92bb7a7d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Primer nombre es requerido</value>
      <webElementGuid>20bf6fc4-f05e-423a-bd77-28c75307e7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenciaPersonal_PrimerNombre</value>
      <webElementGuid>8f395e6c-0b8e-4cb5-a451-eb461abed4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>bc26efbc-bdf6-4afb-8b84-15760663d280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenciaPersonal.PrimerNombre</value>
      <webElementGuid>dca2653b-d3ec-440d-b9ad-db6c933779e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>onlyLetters(event)</value>
      <webElementGuid>0a567930-8aae-4c82-aff2-6ccf3754f0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Primer nombre</value>
      <webElementGuid>82751f4f-b3c7-442a-a137-2bbeb3752842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c2649b6f-0c9f-428e-99d0-0803a13728da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e36e3558-798a-4658-b793-4be3902c5b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenciaPersonal_PrimerNombre&quot;)</value>
      <webElementGuid>b4de6469-aae6-4652-b1f2-ac52a1863b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReferenciaPersonal_PrimerNombre']</value>
      <webElementGuid>2f89832b-01d2-450a-9b92-eb968ace53db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[11]/div/div/input</value>
      <webElementGuid>b7a75093-6533-463a-99bb-f3ba58960c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>6e16a597-79f8-4177-873f-9acf679a042f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReferenciaPersonal_PrimerNombre' and @name = 'ReferenciaPersonal.PrimerNombre' and @placeholder = 'Primer nombre' and @type = 'text']</value>
      <webElementGuid>7df0a83d-f4a3-43dc-bda5-e8bd62c02cac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
