<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Datos Laborales_DatosLaborales.CalleP_e3fd09</name>
   <tag></tag>
   <elementGuidId>b5f8ea81-94d8-444d-9961-d485bf6bed72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatosLaborales_CallePrincipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosLaborales_CallePrincipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3e0caf-dff3-43c2-82e9-ef0687b05b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fbedf408-479e-4795-80af-15fd7fd2f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d92a655-d0f1-4daf-a7cb-e2edfcc24260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 128 caracteres</value>
      <webElementGuid>81a08970-e4af-42a1-a330-00fcfa595708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>22a117be-e797-48fc-b586-04c1c4f42203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Calle principal es requerido</value>
      <webElementGuid>d71fa9ff-9958-45c5-82c4-d394d4ae81a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosLaborales_CallePrincipal</value>
      <webElementGuid>f642dfb5-6a6c-4ae1-9d66-86240ad219dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>6d65b64b-cf7a-43ac-87c9-6d008e98e3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosLaborales.CallePrincipal</value>
      <webElementGuid>d7b89dce-50ac-4c6a-8629-17f3a26f2ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Calle principal</value>
      <webElementGuid>961ebb7f-7a54-466f-a1c2-e695d7fe5a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a13ab388-477a-4514-9caf-d805e4af8354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>547fd09c-c631-48a2-a56e-c890a3c84794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosLaborales_CallePrincipal&quot;)</value>
      <webElementGuid>5112e04c-bc8f-450b-9022-eb8cbbbe4b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatosLaborales_CallePrincipal']</value>
      <webElementGuid>53f23594-fe82-426a-ac48-6a09de3406d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[7]/div[3]/div/input</value>
      <webElementGuid>29252dc2-24e9-4456-8744-a5327a5eea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/input</value>
      <webElementGuid>1bd1e0b5-5b80-4350-b50c-22923462bf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DatosLaborales_CallePrincipal' and @name = 'DatosLaborales.CallePrincipal' and @placeholder = 'Calle principal' and @type = 'text']</value>
      <webElementGuid>bcba085b-12e9-4f93-a98c-e217d50bcb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
