<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lo que tienes y lo que debes_TotalIngresos</name>
   <tag></tag>
   <elementGuidId>a711929f-a688-4809-b5fa-be20d326d447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TotalIngresos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TotalIngresos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ceb34a2-053b-4878-ae64-c352cb9a5d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f0958847-6f11-412b-a7d4-406e50f5aa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c384084-d61b-4d9f-abce-cc1e4c473cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Valor activos must be a number.</value>
      <webElementGuid>de0fb046-3fdf-4f99-a1bb-ef2f1b8f5b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Valor activos es requerido</value>
      <webElementGuid>48fb65e4-c536-4169-8d7e-2b02ac742629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TotalIngresos</value>
      <webElementGuid>0535c3a4-5fd0-439f-9ce9-d9fd0e22a29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>014f4359-f69c-41b6-8c9a-a2a679bbc9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TotalIngresos</value>
      <webElementGuid>2830de8d-2fa1-42d1-9b74-c1145159e2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return filterFloat(event,this);</value>
      <webElementGuid>1db43ef0-0a39-4b6e-b586-17ef5ba4ee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$ Valor de lo que tienes</value>
      <webElementGuid>bf037da5-a887-47c9-977f-6be29292620e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>2cc06a17-0a70-4462-a3bc-304b45957579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4c61126-3589-46f0-a173-b01ec487b571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TotalIngresos&quot;)</value>
      <webElementGuid>1f0bfa35-addf-4131-8182-4bdb2b94a771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TotalIngresos']</value>
      <webElementGuid>d62e657f-8c5f-4035-a145-05ccd662279e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosFinancieros']/div/div/div/div/div/fieldset/div/div[2]/div/div/input</value>
      <webElementGuid>092a15c4-566a-4caf-afb1-21466c8a07bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a7c35fb9-54f8-49a5-adbe-f5b2adf282fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TotalIngresos' and @name = 'TotalIngresos' and @placeholder = '$ Valor de lo que tienes' and @type = 'text']</value>
      <webElementGuid>76e94581-e2da-4b62-981c-036354ff6df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
