<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referencia Personal_ReferenciaPersona_fcc3c8</name>
   <tag></tag>
   <elementGuidId>51eabd78-6a65-4a92-874b-f80612a8d59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReferenciaPersonal_PrimerApellido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReferenciaPersonal_PrimerApellido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>969255f9-b793-4e72-b6fa-722941c19406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1cf20bfa-083e-4e5e-a995-a9fb5ce34102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57cbf29c-3e08-4426-8236-e809d60218ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 32 caracteres</value>
      <webElementGuid>7ca47380-7d93-453d-a263-fcc8ee663dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>2ed429e1-bb66-464f-820b-9efe8e18a17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Primer apellido es requerido</value>
      <webElementGuid>8647bf90-8c75-4649-afe5-1d97d896ac99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenciaPersonal_PrimerApellido</value>
      <webElementGuid>a79b10e2-eae1-4cde-89a0-05fc691eef3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>ce6ff0ed-acf7-4f33-a715-005beaf306f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenciaPersonal.PrimerApellido</value>
      <webElementGuid>f5c38109-0416-43bd-a591-6162c4df8f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>onlyLetters(event)</value>
      <webElementGuid>eb196fbd-adf6-4b88-9617-cae7e2704242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Primer apellido</value>
      <webElementGuid>f34a5c8d-9e1e-4908-8c2c-d0a550b1e86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>92bc5342-63a3-469a-85b9-eb3222f71985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94878b36-04e6-463b-966b-d8d03fbffe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenciaPersonal_PrimerApellido&quot;)</value>
      <webElementGuid>d4dd65a8-6cf7-4595-811d-38dd7507136f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReferenciaPersonal_PrimerApellido']</value>
      <webElementGuid>d5ec99db-86fa-4264-b903-1aac3901b528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[11]/div[2]/div/input</value>
      <webElementGuid>6c51d0f8-e669-424a-a8b6-d334627fcc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/input</value>
      <webElementGuid>2c9e6208-0610-45a9-95f1-27cb79714609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReferenciaPersonal_PrimerApellido' and @name = 'ReferenciaPersonal.PrimerApellido' and @placeholder = 'Primer apellido' and @type = 'text']</value>
      <webElementGuid>52e2ca6c-91eb-40d0-bb91-17634d39398a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
