<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Datos Laborales_DatosLaborales.CalleT_7e0291</name>
   <tag></tag>
   <elementGuidId>e6d80616-abb8-4927-bb11-5881a34a3d7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatosLaborales_CalleTransversal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosLaborales_CalleTransversal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33500aa3-dcae-4730-9cff-127ef8193756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8b0bc809-5b6e-4777-9fd8-ad0236fe8ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b39a83cb-e8a4-473c-a4c8-563c4394deb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 64 caracteres</value>
      <webElementGuid>5519ee6a-d1ce-4be9-b7fa-cffbcad96252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>742eb6cf-711e-4c30-8583-895c5b439e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Calle transversal es requerido</value>
      <webElementGuid>4be2be21-66f6-4d4b-b8d4-220cc5fc1183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosLaborales_CalleTransversal</value>
      <webElementGuid>75bb3b6d-ab18-4361-9158-4e6b282c5b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>b2932ffd-51b2-477f-89b8-fb72d81ddd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosLaborales.CalleTransversal</value>
      <webElementGuid>868cdde7-96e9-4ee5-906a-7ead3967cbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Calle transversal</value>
      <webElementGuid>a634f8ec-6c02-4636-a995-9f4435465725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>85c4f394-faad-419b-8d8b-e78a2e8fed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35d93783-0854-4f2f-976c-16705ad585ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosLaborales_CalleTransversal&quot;)</value>
      <webElementGuid>f3ab02df-0e5b-459a-a39a-967e5881dfde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatosLaborales_CalleTransversal']</value>
      <webElementGuid>f976738b-3eb7-42be-a89b-5a27787881a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[8]/div[2]/div/input</value>
      <webElementGuid>ece4b3bd-8a8c-409f-b741-bfb1affee128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/input</value>
      <webElementGuid>3598a54e-c2a6-4762-87b8-b3a1a18b6823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DatosLaborales_CalleTransversal' and @name = 'DatosLaborales.CalleTransversal' and @placeholder = 'Calle transversal' and @type = 'text']</value>
      <webElementGuid>68a954d3-b86b-4de8-8bb9-9c87d13cfd6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
