<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Datos de tu domicilio_DatosDomicilio._cd9c25</name>
   <tag></tag>
   <elementGuidId>c427ed10-00fb-434f-b46e-83335be67966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DatosDomicilio_NumeroCasa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosDomicilio_NumeroCasa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>967ad1bf-6b41-4612-bcdb-d5c21aa45875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a63bbba-a632-4cda-b236-8f33d5ecee36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>445c3bc7-2a5f-4631-b6a2-819b80669732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 16 caracteres</value>
      <webElementGuid>a9ebfbbe-cedd-45a4-b76e-68c9b7f42e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>3e7b476e-acdf-47a0-bd7f-a1b9b0687c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Número de casa es requerido</value>
      <webElementGuid>ee028752-417a-447a-8c55-3e564da9d459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosDomicilio_NumeroCasa</value>
      <webElementGuid>f85351b7-770a-4ada-bd23-e1ac2d54da09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>58fc2d67-001f-4145-ab8c-6cd135cd4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosDomicilio.NumeroCasa</value>
      <webElementGuid>8d570dee-7838-42dc-91ea-8539870d51de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número de casa</value>
      <webElementGuid>f3acbe67-c8a3-4380-b9bc-3e1cbb3c9428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>5e9946ee-7f76-4a47-a17c-190a98046423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd27b358-f399-4c7a-95d2-85dd3418a096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosDomicilio_NumeroCasa&quot;)</value>
      <webElementGuid>540c393a-2993-4c6f-a4ae-342606d0483a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DatosDomicilio_NumeroCasa']</value>
      <webElementGuid>84ca48ee-4c56-4b88-abc1-d90b647d7c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[3]/div[3]/div/input</value>
      <webElementGuid>419c8344-3cc8-4305-8571-2bac7f749acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>593fb829-c53c-4bd6-ba46-0491ad1b9ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DatosDomicilio_NumeroCasa' and @name = 'DatosDomicilio.NumeroCasa' and @placeholder = 'Número de casa' and @type = 'text']</value>
      <webElementGuid>3df74737-d2e5-4174-ac3a-429f8db3b746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
