<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BarrioCDLA UNION CARCHENCE COOP LUCH_77d9b5</name>
   <tag></tag>
   <elementGuidId>00dcf00e-9f13-40b6-b817-e9f9c0e6828a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DatosDomicilio_CodigoBarrio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosDomicilio_CodigoBarrio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bd19b31-a86e-4f2c-9197-90aa0c9199e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>983e4d2d-b11e-4ab0-9e04-2f4cd0a406dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1435bfd5-8ef3-4ae9-9e4e-403ccb07f16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Barrio  es requerido</value>
      <webElementGuid>270f54da-daa4-46eb-9a37-d750a708d916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosDomicilio_CodigoBarrio</value>
      <webElementGuid>561c4505-9346-46b7-9bcf-7f77db34ee09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosDomicilio.CodigoBarrio</value>
      <webElementGuid>6198b567-5132-4c26-bc4e-b20f1c8ac55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>49e38b4e-0e93-4392-a6a2-ecb8e7d543a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ae85e2ed-5bcf-4793-8467-f6fc8a8a751d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BarrioCDLA UNION CARCHENCE COOP LUCHA DE LOS POBRESGUAJALOPUEBLO UNIDOSAN BLAS 2SAN MARTIN VALLE DEL SUR </value>
      <webElementGuid>a3ab5417-88b1-4b28-a773-dc37df48d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosDomicilio_CodigoBarrio&quot;)</value>
      <webElementGuid>ca0cf96e-c6c1-49cd-98cb-f3f376be8eeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DatosDomicilio_CodigoBarrio']</value>
      <webElementGuid>d81df981-d739-49c9-a804-211cfb5f7131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[3]/div/div/select</value>
      <webElementGuid>91a4f1c4-5bb3-4e3d-b477-c32af19cc2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de tu domicilio'])[1]/following::select[4]</value>
      <webElementGuid>b86ce524-c79e-47dd-9e59-f5cd080aebc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayúdanos con los siguientes datos, estos son importantes para poder continuar con tu crédito.'])[1]/following::select[4]</value>
      <webElementGuid>d75f25f0-bdb8-4d58-969e-4511813a9261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Laborales'])[1]/preceding::select[1]</value>
      <webElementGuid>41c157fe-4ded-425d-9ab0-b89ea185fb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justificativo de Ingresos'])[1]/preceding::select[5]</value>
      <webElementGuid>6ec63a30-74e3-48dd-b666-01a370dd858b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>a6fd81e4-2938-4f6c-9be2-d8f43b4dd764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DatosDomicilio_CodigoBarrio' and @name = 'DatosDomicilio.CodigoBarrio' and (text() = 'BarrioCDLA UNION CARCHENCE COOP LUCHA DE LOS POBRESGUAJALOPUEBLO UNIDOSAN BLAS 2SAN MARTIN VALLE DEL SUR ' or . = 'BarrioCDLA UNION CARCHENCE COOP LUCHA DE LOS POBRESGUAJALOPUEBLO UNIDOSAN BLAS 2SAN MARTIN VALLE DEL SUR ')]</value>
      <webElementGuid>a5f0a201-a577-43bc-a99c-3496ebf9c94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
