<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BarrioAGLLABARRIOS NO DEFINIDOSCENTR_7e6b40</name>
   <tag></tag>
   <elementGuidId>9e8ec58e-391b-4c65-8ed3-7caf5494f347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DatosLaborales_CodigoBarrio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosLaborales_CodigoBarrio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68ba0f66-df99-4fb8-b3ce-1199a89b852d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb84adff-8b1f-42f9-af9f-a41219ff66b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61406a52-a885-4797-a487-ab916d943dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Barrio es requerido</value>
      <webElementGuid>35c4d083-169c-4097-a82f-8f7af2675f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosLaborales_CodigoBarrio</value>
      <webElementGuid>068a73e0-c3a7-4817-a678-b88d5fa95cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosLaborales.CodigoBarrio</value>
      <webElementGuid>f6f3e34a-5700-4217-bfa4-8facbd73ee3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>b96b7b9c-cce6-416d-b26e-84852b3c2cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>970403a2-bbc6-4c0f-bce8-96149c2e1c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BarrioAGLLABARRIOS NO DEFINIDOSCENTROCHECACHILPA COMUNA EL CARMENCOMUNA GUADALUPECUSCUNGOESTELLA MARISLA DELICIALA NUEVA ESPERANZALA TOLALALAGACHIMOLINO PAMBANUEVA ESPERANZA NUEVA UNIÓNSAN AGUSTINSAN JUANSAN PEDRO DE LA TOLASELVA ALEGRETOLA ALTAZAMORA</value>
      <webElementGuid>c19f4726-c83d-4cc1-bc21-2029eb27b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosLaborales_CodigoBarrio&quot;)</value>
      <webElementGuid>14ddf4e0-0fb2-4487-b8e1-60ec5f671e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DatosLaborales_CodigoBarrio']</value>
      <webElementGuid>3968ebef-03c3-4efd-99a5-e71d3a717c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[7]/div[2]/div/select</value>
      <webElementGuid>36443e54-a67a-49e1-bfde-6116b3a8e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Laborales'])[1]/following::select[4]</value>
      <webElementGuid>a71d5355-ec61-4c2a-acc8-04f800e3d6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de tu domicilio'])[1]/following::select[8]</value>
      <webElementGuid>f29782c0-b1fe-46c7-80bb-2b553ca2a4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justificativo de Ingresos'])[1]/preceding::select[1]</value>
      <webElementGuid>ab422805-32ae-478a-b807-8e95ee40e61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/select</value>
      <webElementGuid>66fe7914-4aa0-4012-a239-e3f761848c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DatosLaborales_CodigoBarrio' and @name = 'DatosLaborales.CodigoBarrio' and (text() = 'BarrioAGLLABARRIOS NO DEFINIDOSCENTROCHECACHILPA COMUNA EL CARMENCOMUNA GUADALUPECUSCUNGOESTELLA MARISLA DELICIALA NUEVA ESPERANZALA TOLALALAGACHIMOLINO PAMBANUEVA ESPERANZA NUEVA UNIÓNSAN AGUSTINSAN JUANSAN PEDRO DE LA TOLASELVA ALEGRETOLA ALTAZAMORA' or . = 'BarrioAGLLABARRIOS NO DEFINIDOSCENTROCHECACHILPA COMUNA EL CARMENCOMUNA GUADALUPECUSCUNGOESTELLA MARISLA DELICIALA NUEVA ESPERANZALA TOLALALAGACHIMOLINO PAMBANUEVA ESPERANZA NUEVA UNIÓNSAN AGUSTINSAN JUANSAN PEDRO DE LA TOLASELVA ALEGRETOLA ALTAZAMORA')]</value>
      <webElementGuid>3f86aae0-4ecf-4a8b-a11d-70338a353118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
