<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CantnCAYAMBEMEJIAPEDRO MONCAYOPEDRO _aade4a_1</name>
   <tag></tag>
   <elementGuidId>c70b129b-97b2-4358-be64-0e69bbb05aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DatosLaborales_CodigoCanton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosLaborales_CodigoCanton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e2eec3b7-4b75-4734-8f21-e31e633561b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c680c333-5776-4d88-89b0-3102443003e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58d90772-bdec-4563-a597-57bd5d75c95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Cantón es requerido</value>
      <webElementGuid>aa1ce3b6-bdd4-40b6-818a-a734a065713b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosLaborales_CodigoCanton</value>
      <webElementGuid>499685b9-f459-4078-a5ea-6d5e06706777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosLaborales.CodigoCanton</value>
      <webElementGuid>0b0d687c-0fc7-4bee-ab39-affc9697a7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ObtieneParroquiasDatosLaborales();</value>
      <webElementGuid>a1fec68b-64de-41b3-a149-3a93d6e66821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>ea8d2f19-021e-411a-9e72-c0f6051adb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Seleccione el Cantón')</value>
      <webElementGuid>2b9b6243-7b61-4da4-96ff-a2fcb03a8fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>304de155-2299-453c-853b-27d3a6d394a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CantónCAYAMBEMEJIAPEDRO MONCAYOPEDRO VICENTE MALDONADOPUERTO QUITOQUITORUMIÑAHUISAN MIGUEL DE LOS BANCOS</value>
      <webElementGuid>5d13811b-7639-434a-822a-e0912d0e7800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosLaborales_CodigoCanton&quot;)</value>
      <webElementGuid>18230a47-570b-4a53-b1da-997db3fb9309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DatosLaborales_CodigoCanton']</value>
      <webElementGuid>09404c23-2293-4168-84e5-0f7dbba52b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[6]/div[3]/div/select</value>
      <webElementGuid>2d756f9d-ab08-4c7a-95fd-28a04c7bcecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Laborales'])[1]/following::select[2]</value>
      <webElementGuid>4a83c699-7ae6-42f4-80b5-21eced47d6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de tu domicilio'])[1]/following::select[6]</value>
      <webElementGuid>7a6291dd-3b58-40c1-a003-9b42f614470e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justificativo de Ingresos'])[1]/preceding::select[3]</value>
      <webElementGuid>4164cb9f-4905-42ff-a707-37693b843008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/select</value>
      <webElementGuid>8955a138-1207-4e35-8f80-37ea5ff2be1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DatosLaborales_CodigoCanton' and @name = 'DatosLaborales.CodigoCanton' and (text() = 'CantónCAYAMBEMEJIAPEDRO MONCAYOPEDRO VICENTE MALDONADOPUERTO QUITOQUITORUMIÑAHUISAN MIGUEL DE LOS BANCOS' or . = 'CantónCAYAMBEMEJIAPEDRO MONCAYOPEDRO VICENTE MALDONADOPUERTO QUITOQUITORUMIÑAHUISAN MIGUEL DE LOS BANCOS')]</value>
      <webElementGuid>a068941a-9db3-4294-87d8-80f7a9035802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
