<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ParroquiaALANGASAMAGUAAATAHUALPABELI_e750cb</name>
   <tag></tag>
   <elementGuidId>87d98abd-e6ea-4512-a66b-81ba85079ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DatosDomicilio_CodigoParroquia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosDomicilio_CodigoParroquia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2050231b-a9fb-4487-af3b-645c5574a6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>688408f2-0ca7-4aab-af11-c6c27eaea5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32b8f76a-8b52-4a69-a9cb-fd087d672f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Parroquia es requerido</value>
      <webElementGuid>6a861db2-4c97-46ca-885f-fc8d2c7af83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosDomicilio_CodigoParroquia</value>
      <webElementGuid>78bf2892-859e-4e5d-80e1-0bda6c217a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosDomicilio.CodigoParroquia</value>
      <webElementGuid>b77a40d7-5145-4e45-98fb-100af9811ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ObtieneBarrios();</value>
      <webElementGuid>a162a9bb-f7d0-45a8-b25a-80be6833d58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>66442950-3eb8-40aa-9cb6-3ad78f6c3c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Seleccione el barrio')</value>
      <webElementGuid>9002e0ce-436b-4214-bcb2-59b604f0965a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c257cd13-a0cd-4c77-807f-806ae961728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA</value>
      <webElementGuid>b007d513-ee03-4fd3-aee9-474a92c48dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosDomicilio_CodigoParroquia&quot;)</value>
      <webElementGuid>1f90e106-b92b-4919-8c5f-7a9cf688c307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DatosDomicilio_CodigoParroquia']</value>
      <webElementGuid>9aa352a7-cc91-4f3c-a982-445cf8d31505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[2]/div[3]/div/select</value>
      <webElementGuid>e3199db6-1c87-440c-8e68-6041c65269c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de tu domicilio'])[1]/following::select[3]</value>
      <webElementGuid>d08ee680-1654-4b3c-8f97-3ea3749d0787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayúdanos con los siguientes datos, estos son importantes para poder continuar con tu crédito.'])[1]/following::select[3]</value>
      <webElementGuid>9f58a986-32da-4eb6-a416-d868ef2f8e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Laborales'])[1]/preceding::select[2]</value>
      <webElementGuid>c8fac5c8-14a0-45fb-b2b7-2045530185c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justificativo de Ingresos'])[1]/preceding::select[6]</value>
      <webElementGuid>b7bf91aa-489e-4e11-a550-8b8a863e23ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>926271d7-e126-45b9-87ba-947aba1b6596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DatosDomicilio_CodigoParroquia' and @name = 'DatosDomicilio.CodigoParroquia' and (text() = 'ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA' or . = 'ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA')]</value>
      <webElementGuid>509c2040-99c4-4533-99d2-a536b09e4a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
