<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ParroquiaALANGASAMAGUAAATAHUALPABELI_e750cb_1</name>
   <tag></tag>
   <elementGuidId>314143e5-d9ac-4ac0-9a8d-d2c6bde6a54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DatosLaborales_CodigoParroquia']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatosLaborales_CodigoParroquia</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>47913d41-0987-4237-8036-8ad497e19177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ccf909a2-484f-4b2b-821d-8199f7fec8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b90929b-f2ce-4a10-80d3-65fab3688aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Parroquia es requerido</value>
      <webElementGuid>a26e10e6-4746-41c4-9610-4a968edd9def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DatosLaborales_CodigoParroquia</value>
      <webElementGuid>a1504582-05bc-42c1-92bb-2d2c73780f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DatosLaborales.CodigoParroquia</value>
      <webElementGuid>86b4af6a-0c52-401c-99ab-a4f2b12ffcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ObtieneBarriosDatosLaborales();</value>
      <webElementGuid>c163a8ed-fab9-4e4e-bdb6-84be575d2b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>2ede1e3b-db9e-4e0f-894c-e026e3d0de62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Seleccione el barrio')</value>
      <webElementGuid>2b486295-1c1e-4dcc-9dfe-81a50a36d4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>abc256ad-647f-4863-95c4-48ec6facdd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA</value>
      <webElementGuid>7b321f78-6ac5-44f8-962a-8f03d487da38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatosLaborales_CodigoParroquia&quot;)</value>
      <webElementGuid>60c7d46c-ceab-4080-a2d9-efbf6c253e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DatosLaborales_CodigoParroquia']</value>
      <webElementGuid>2707fa41-b114-4b62-a26e-8e58553e69b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[7]/div/div/select</value>
      <webElementGuid>bf0dbf5d-87d6-4e87-bf3e-ad5a52d83c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Laborales'])[1]/following::select[3]</value>
      <webElementGuid>5acc9db1-8836-4e4c-ab63-c4d47ce34e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de tu domicilio'])[1]/following::select[7]</value>
      <webElementGuid>8c688f81-f0d9-43d2-9372-e0af9bdc41f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Justificativo de Ingresos'])[1]/preceding::select[2]</value>
      <webElementGuid>667d7601-2778-4c19-a847-3b91f673cae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>c4b45fd5-550e-472a-b0da-3b7ed341f61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DatosLaborales_CodigoParroquia' and @name = 'DatosLaborales.CodigoParroquia' and (text() = 'ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA' or . = 'ParroquiaALANGASÍAMAGUAÑAATAHUALPABELISARIO QUEVEDOCALACALÍCALDERÓNCARCELÉNCENTRO HISTORICOCHAVEZPAMBACHECACHILIBULOCHILLOGALLOCHIMBACALLECOCHAPAMBACOMITÉ DEL PUEBLOCONOCOTOCOTOCOLLAOCUMBAYÁEL CONDADOEL QUINCHEGUAJALOGUALEAGUAMANÍGUANGOPOLOGUAYLLABAMBAIÑAQUITOITCHIMBIAJIPIJAPAKENNEDYLA ARGELIALA CONCEPCIONLA ECUATORIANALA FERROVIARIALA LIBERTADLA MAGDALENALA MENALA MERCEDLLANO CHICOLLANO GRANDELLOAMARISCAL SUCREMENA 2NANEGALNANEGALITONAYÓNNONOPACTOPERUCHOPIFOPÍNTAGPOMASQUIPONCEANOPUÉLLAROPUEMBOPUENGASÍQUITUMBERUMIPAMBASAN ANTONIO DE PICHINCHASAN BARTOLOSAN ISIDRO DEL INCASAN JOSÉ DE MINASSAN JUANSOLANDATABABELATUMBACOTURUBAMBAYARUQUÍZAMBIZA')]</value>
      <webElementGuid>bad88f39-a1c3-4527-8bc6-e8cdbe46afa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
