<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_meses_Continuar</name>
   <tag></tag>
   <elementGuidId>a8510531-a439-4048-b834-72d91a10b18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Continuar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Continuar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5da10f9b-fe08-462d-aa85-6a7daa48dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/Aplica-ahora.png</value>
      <webElementGuid>712fc837-d4c5-44da-80f8-913883c04c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bntAplicaAhora</value>
      <webElementGuid>a210b2d3-0959-4b90-9a13-5741d0ea6b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>e17c571c-27a1-4961-9aeb-45772a09f9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Continuar&quot;)</value>
      <webElementGuid>ed601604-f538-4775-8b03-336fccc473f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Continuar']</value>
      <webElementGuid>9e2c25db-8546-445f-a320-21f227702289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/div[2]/div/div[2]/div/img</value>
      <webElementGuid>802743b8-b17e-4a28-85c6-aa526887f8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>8f800ae1-4333-4789-8ac2-735c486895ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/Aplica-ahora.png' and @id = 'Continuar']</value>
      <webElementGuid>3c460fcc-e364-4c21-bf66-72483371d97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
