<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Campaa (1)</name>
   <tag></tag>
   <elementGuidId>57f8ee10-ea34-4d4d-bb2e-b35aa7581c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPresentarOfertasBotonConfirmacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='modal-content']/div[@class='modal-footer']/button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6460e690-b555-4a25-af86-ada5ffe09ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d2410e9-1f2d-4e2c-a17d-13fad6ab1ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPresentarOfertasBotonConfirmacion</value>
      <webElementGuid>10ab66e2-3d9c-4635-b23b-d65d9777f2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>06421bf5-d3b2-4524-863a-581cf87cf280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5d552b0-0bc5-4a2d-8444-31622d65533b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Campaña</value>
      <webElementGuid>2612e9ff-9f1c-4658-b166-9b4c8ed9a9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPresentarOfertasBotonConfirmacion&quot;)</value>
      <webElementGuid>61c38763-c3bb-46e6-825b-20bf14056279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      <webElementGuid>6e44edf8-335d-4dcc-a502-0a22ef4ab41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      <webElementGuid>53b6d4a3-6c9b-44dc-a6bd-a765a4f3ca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>71423cad-0bb2-4414-9f1f-140923f4faad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$152.00'])[1]/following::button[2]</value>
      <webElementGuid>d28c5de0-9184-42a9-8013-ea94f573ec51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Generadas'])[1]/preceding::button[2]</value>
      <webElementGuid>c05e9fa2-e3ba-4017-94eb-f374c8d13ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Generación'])[1]/preceding::button[2]</value>
      <webElementGuid>4ba947f3-6464-49d0-8e54-abaffc9521ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Campaña']/parent::*</value>
      <webElementGuid>5ec93465-4366-4eb3-baa2-b2b6a2d2970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button[2]</value>
      <webElementGuid>fc534e14-5338-40ab-a93e-4062aacb0d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'modalPresentarOfertasBotonConfirmacion' and (text() = 'Generar Campaña' or . = 'Generar Campaña')]</value>
      <webElementGuid>b629f252-54a9-448b-89fc-7fbdbabd9d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
