<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ofertar (2)</name>
   <tag></tag>
   <elementGuidId>86343414-59a8-4fd1-8e2f-07e03425cb7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[23]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ad8b701-a1db-4502-a883-40ee13df89eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c96621f8-d1e1-4e9d-9179-7b9193147110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success oferta</value>
      <webElementGuid>c8b902e5-df10-434c-b8e3-cc28f7ccb1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PresentarOfertasGeneradas('UniCrédito Inmediato', 4700.00, 48, 152.00, null, 'UNIINM', true);</value>
      <webElementGuid>ae1e8bef-4972-453d-8adc-b1c1a6ec3b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8679701-c050-45c4-84a9-71ec43ace47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ofertar</value>
      <webElementGuid>3be24a1e-f60e-4b9f-85f3-f1fa181e343a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementosOfertas&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;box box-default&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;info-box&quot;]/div[@class=&quot;info-box-content&quot;]/span[@class=&quot;info-box-number&quot;]/span[1]/button[@class=&quot;btn btn-success oferta&quot;]</value>
      <webElementGuid>bdec602e-c92e-40bf-b0e8-5a5c78323055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>224d28c9-6ed9-4775-828a-6633adc5c4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementosOfertas']/div[2]/div/div[2]/div/div/span[4]/span/button</value>
      <webElementGuid>2fdfabe5-795f-4b9a-a428-a2c8fda40c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 4700.00'])[2]/following::button[1]</value>
      <webElementGuid>62e507c1-0f62-4ab9-85e0-557677295e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(48 meses)'])[2]/following::button[1]</value>
      <webElementGuid>9cdcd16f-2e1d-4383-912f-7b4859b0eeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alia Inmediato'])[1]/preceding::button[1]</value>
      <webElementGuid>ee8ad341-51ec-4a2b-9164-d5fadcd21347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1400.00'])[1]/preceding::button[2]</value>
      <webElementGuid>fe4bffcf-9a67-4a1a-8401-82bf63bf8b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span[4]/span/button</value>
      <webElementGuid>1831f39b-9579-4d04-bc86-711682fe4da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ofertar' or . = 'Ofertar')]</value>
      <webElementGuid>81afb55c-535f-4780-95a0-db970b5b1263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
