<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Oferta</name>
   <tag></tag>
   <elementGuidId>474f1b5b-85f4-46b6-b6d7-6ea12ddabbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonGenerarOfertas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#botonGenerarOfertas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89b70ff3-a30b-4cde-858a-8e0c3054bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>481335d8-abbf-4601-9b8c-e550b25c25da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonGenerarOfertas</value>
      <webElementGuid>9b143feb-d637-4f53-bcdb-165e08168c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>aeededb4-fd76-4008-8d3d-aac2bb62e4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06cbe92d-6cc2-4f9c-b3fc-c2b68395b7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Oferta</value>
      <webElementGuid>e3f1ad89-c78a-416d-9110-17c94cd8f5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonGenerarOfertas&quot;)</value>
      <webElementGuid>5739f43e-7648-4b73-87c1-352acc98770e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonGenerarOfertas']</value>
      <webElementGuid>2d04f18b-0205-4c5c-b6a2-3c07ba12221f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultadosCliente']/div[3]/button</value>
      <webElementGuid>78ff88c1-1e5f-4d35-aa21-f95d6227ab91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/following::button[1]</value>
      <webElementGuid>76f74768-23c7-4273-b80e-0bbe8b097d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras Cuotas'])[2]/following::button[1]</value>
      <webElementGuid>6d295a1e-d5cd-4136-b1bb-54244b823d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación UC Activa'])[1]/preceding::button[1]</value>
      <webElementGuid>df394e92-945a-466a-a11c-287b9ed6a7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALDO OPERACIÓN UC ACTIVA'])[1]/preceding::button[2]</value>
      <webElementGuid>da05b2ec-3148-4756-9cd8-f087f48c069d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Oferta']/parent::*</value>
      <webElementGuid>43d13bb3-66ef-48bd-aeaf-b3646859c094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/button</value>
      <webElementGuid>c8e05f43-65c3-4f52-9691-f40eb36963b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonGenerarOfertas' and (text() = 'Generar Oferta' or . = 'Generar Oferta')]</value>
      <webElementGuid>e22a187f-a731-484f-932d-cded42c8f4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
