<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Campaa</name>
   <tag></tag>
   <elementGuidId>afcc0443-ad92-4195-b011-ab261131657c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modalPresentarOfertasBotonConfirmacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fee3cd0d-071d-4a8b-ba12-84fd3556c81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d33b423f-2e69-4441-aba5-ef5b00759543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPresentarOfertasBotonConfirmacion</value>
      <webElementGuid>2789b2ed-bb5e-4da9-8cdf-b8024d228302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d452ddf0-28b6-4dd9-9efa-380999df9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e02bdc1-2b63-4fc6-a816-5e8c82569bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Campaña</value>
      <webElementGuid>af816e1d-a205-4a07-8631-9b62080fd06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPresentarOfertasBotonConfirmacion&quot;)</value>
      <webElementGuid>9a3a2e5f-5de2-4bae-b1fb-41a69f210ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      <webElementGuid>a60bab7a-d519-48fd-a5ef-c61b7877a365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      <webElementGuid>3183bb58-7f2c-480e-a398-3f060ccfe86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>bc685fa2-45fd-4d65-996c-363ec7697152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1100.00'])[2]/following::button[2]</value>
      <webElementGuid>9accf979-b948-4b97-8fce-249dca311742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Generadas'])[1]/preceding::button[2]</value>
      <webElementGuid>68198c95-05ba-4f2c-90da-42803ca0ff2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Generación'])[1]/preceding::button[2]</value>
      <webElementGuid>c9fecfb5-a1be-458a-8353-382dc108b116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Campaña']/parent::*</value>
      <webElementGuid>2eea546e-0cd9-4508-a3bc-cf322d9b332b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button[2]</value>
      <webElementGuid>1ff74109-a7e1-4e92-8c72-57e77a3be40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'modalPresentarOfertasBotonConfirmacion' and (text() = 'Generar Campaña' or . = 'Generar Campaña')]</value>
      <webElementGuid>c8229961-1aa7-424e-835b-992ae54fc7a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
