<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Oferta</name>
   <tag></tag>
   <elementGuidId>c0f37db7-bb69-42a8-a9dd-849199d7f8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonGenerarOfertas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonGenerarOfertas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0439c0f-f368-4794-bf67-3f46369d2a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a9391ab-5299-4d0c-a39c-21e4baddee46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonGenerarOfertas</value>
      <webElementGuid>1fccf650-96f6-4591-ad04-23cf0b2c2e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>55e1184d-e341-4d8a-8830-c518c65fa8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>316f4699-33ac-4967-9fe1-7e9f8fca6df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Oferta</value>
      <webElementGuid>f44deb62-5257-4545-b567-1c9bc3972438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonGenerarOfertas&quot;)</value>
      <webElementGuid>60d184ba-d520-4b73-b3fe-1379a843702b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonGenerarOfertas']</value>
      <webElementGuid>456db7b2-0a69-4a7c-85bd-a420f517719d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultadosCliente']/div[3]/button</value>
      <webElementGuid>c522f6c9-ef0f-4a62-9751-ec319bfa403a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/following::button[1]</value>
      <webElementGuid>6f030136-901c-4ad8-b3d9-473e26f76d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras Cuotas'])[2]/following::button[1]</value>
      <webElementGuid>17feb7c6-b0c8-4fc9-9acf-68434683823b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación UC Activa'])[1]/preceding::button[1]</value>
      <webElementGuid>ea7dec24-49d2-4bf3-8d0b-a15b38ad8956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALDO OPERACIÓN UC ACTIVA'])[1]/preceding::button[2]</value>
      <webElementGuid>1c92e660-c5d0-404b-b535-ef6513d7bf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Oferta']/parent::*</value>
      <webElementGuid>2da89533-1c02-4c95-b472-9faf46434739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/button</value>
      <webElementGuid>a4931157-f6db-4c9a-b452-b5b1119719cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonGenerarOfertas' and (text() = 'Generar Oferta' or . = 'Generar Oferta')]</value>
      <webElementGuid>43344d6e-e9b5-4a8a-96d6-b039d6ffad37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
