<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacin_inputIdentificacion</name>
   <tag></tag>
   <elementGuidId>b9a544ba-64de-4e9d-97f0-74422b7f1e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>942a5959-8676-43ab-b2bb-7f6e79ab15ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12d5d439-24ac-4137-83de-e08d0ac9c3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f31a9ffa-59fd-46a6-a074-5dd2ca952364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputIdentificacion</value>
      <webElementGuid>e1f47901-b867-428b-ac77-f2fbaede417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese Identificación del Cliente</value>
      <webElementGuid>e18737a5-6771-49d2-8ab4-11d169af9a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae9390c8-8ef3-40a7-8ae4-f2c17503799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputIdentificacion&quot;)</value>
      <webElementGuid>45135b33-cf11-4eb9-ba95-082509adf6b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputIdentificacion']</value>
      <webElementGuid>3cfb8d9f-b9a1-413d-88e4-6a24ffde4b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>158274a7-67b0-4486-9eec-8ae9fdc2a91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>ab741197-0764-495f-a8d7-10c4ce75c291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputIdentificacion' and @placeholder = 'Ingrese Identificación del Cliente']</value>
      <webElementGuid>e468b9d2-87e4-420f-9d12-5c7cc6c23ddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
