<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Campaa</name>
   <tag></tag>
   <elementGuidId>20953eb0-c69a-4675-826f-3aab4af4b549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPresentarOfertasBotonConfirmacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddb2042a-3777-4993-a8da-900cf8899326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65659399-9d06-4181-874d-2832dec693e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPresentarOfertasBotonConfirmacion</value>
      <webElementGuid>b755a649-73ad-4470-9af6-1206b824d544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>fc24f216-bd91-42f3-9904-4fd5e1aeda94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db9a264c-dbd4-4d08-8ebe-b0bc4698ce19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Campaña</value>
      <webElementGuid>43ba93d8-91f5-4eff-8243-d02f865b5b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPresentarOfertasBotonConfirmacion&quot;)</value>
      <webElementGuid>47291498-7d72-481b-9f43-5888658cd742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      <webElementGuid>1a1115c1-5481-4e3d-86a3-181e577346d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      <webElementGuid>a97b2646-11bd-4ab9-ba46-d22851402de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>7d2d2904-e87d-4e4e-a4b2-455e1dbb77d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$300.00'])[1]/following::button[2]</value>
      <webElementGuid>ffde9729-339a-45d9-863c-d8a2fabb48b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Generadas'])[1]/preceding::button[2]</value>
      <webElementGuid>281778b5-d819-42d8-b2e7-5819d6b47e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Generación'])[1]/preceding::button[2]</value>
      <webElementGuid>7fa35bba-a6f6-444d-afc8-aaa638d1c718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Campaña']/parent::*</value>
      <webElementGuid>343f2706-219f-423a-a5a7-3a45af0040a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button[2]</value>
      <webElementGuid>bab3bd67-07ae-4f0b-bc03-950b7f932485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'modalPresentarOfertasBotonConfirmacion' and (text() = 'Generar Campaña' or . = 'Generar Campaña')]</value>
      <webElementGuid>ab27a231-7546-4d8b-89d3-fccd9ccdf4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
