<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Oferta (1)</name>
   <tag></tag>
   <elementGuidId>385e17d7-d944-4a50-821c-77ccb88aa266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonGenerarOfertas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonGenerarOfertas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03ad36ac-cbdb-4dd8-aa4f-350fbb83fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a78f155-1e6e-4651-809e-43ed77ceed45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonGenerarOfertas</value>
      <webElementGuid>23938029-6bae-40c0-89d0-b104ae56aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>57e81a13-533d-40b8-85bc-8789faf3fb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>725f97a4-2233-4053-a7be-5f98bea82e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Oferta</value>
      <webElementGuid>f64cce2a-4765-42ca-8ed7-fcecda476a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonGenerarOfertas&quot;)</value>
      <webElementGuid>a6abbe30-e7f6-42f1-94aa-3b684c2fa8af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonGenerarOfertas']</value>
      <webElementGuid>446314ff-d234-4bd1-86bb-4908d65162d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultadosCliente']/div[3]/button</value>
      <webElementGuid>83a9184f-4cfe-43bf-85de-e27536a0cb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/following::button[1]</value>
      <webElementGuid>b9ed627c-8aa2-4b21-b010-885edd4e241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras Cuotas'])[2]/following::button[1]</value>
      <webElementGuid>cf907d16-db12-4af9-beec-522abec8fb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación UC Activa'])[1]/preceding::button[1]</value>
      <webElementGuid>b548ad06-9c42-44e5-8a65-e532deb655c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALDO OPERACIÓN UC ACTIVA'])[1]/preceding::button[2]</value>
      <webElementGuid>1eae73f9-9ea4-4924-bdfd-a30ed4251158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Oferta']/parent::*</value>
      <webElementGuid>dd1ffab2-f82b-4430-9d44-47e65f2b3da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/button</value>
      <webElementGuid>3816e922-42e4-40eb-9703-12424ae3a7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonGenerarOfertas' and (text() = 'Generar Oferta' or . = 'Generar Oferta')]</value>
      <webElementGuid>eefaf35a-bd9c-4a31-b912-d517c63361fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
