<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Oferta</name>
   <tag></tag>
   <elementGuidId>c9589b54-2815-4b5f-840e-3f50828af511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonGenerarOfertas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonGenerarOfertas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0fce27e-5f6e-4614-a15a-f58a193045c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aecb19f4-b0df-4d4b-a5ac-8323e9bf55d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonGenerarOfertas</value>
      <webElementGuid>90414859-46b4-4840-bd6a-2b32c03e6dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>2f9c7114-ec6c-4ae5-9d7e-15bf7860564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb7e7aa0-12ad-4936-a67d-ed6f5b778668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Oferta</value>
      <webElementGuid>9863c2ab-e17e-4c55-b98e-efade6819b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonGenerarOfertas&quot;)</value>
      <webElementGuid>64a8286b-00a1-4dcb-a8a1-4201af07b505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonGenerarOfertas']</value>
      <webElementGuid>61cdbd0b-cdf1-40d9-a5f4-513b995f5dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultadosCliente']/div[3]/button</value>
      <webElementGuid>024c3faf-18e5-4fd1-ace8-04bb33d3e07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/following::button[1]</value>
      <webElementGuid>3998ac8d-cef3-4a62-a54a-1480d333a34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras Cuotas'])[2]/following::button[1]</value>
      <webElementGuid>e7b90a35-bd6d-4e42-adf8-fbb2e481f0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación UC Activa'])[1]/preceding::button[1]</value>
      <webElementGuid>7882ca66-ad1f-4f51-b242-39ea79c05237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALDO OPERACIÓN UC ACTIVA'])[1]/preceding::button[2]</value>
      <webElementGuid>799b3786-5c2f-49e6-85cf-bca3bffc60a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Oferta']/parent::*</value>
      <webElementGuid>38e4205e-0b4f-4d3e-95c6-18f14cc190ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/button</value>
      <webElementGuid>e5a0b6f8-5813-4425-9f7a-73a6b3a9950a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonGenerarOfertas' and (text() = 'Generar Oferta' or . = 'Generar Oferta')]</value>
      <webElementGuid>62f9619a-6eb3-4bea-90f7-3b806243a30b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
