<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alia Inmediato 700.00Ofertar</name>
   <tag></tag>
   <elementGuidId>a0645f59-70c3-44e5-add5-d5e94ea5633b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementosOfertas']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6738bbb-5c51-4ef1-bf5e-3f4b072e0c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box box-default</value>
      <webElementGuid>c2f0f245-e9f9-4786-b25b-f709702393ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alia Inmediato$ 700.00Ofertar</value>
      <webElementGuid>3a99cb6b-9774-4d7b-88e7-bfd026e05d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementosOfertas&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;box box-default&quot;]</value>
      <webElementGuid>a8931d1c-c7ac-481c-b9f4-090094dac528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementosOfertas']/div[3]/div</value>
      <webElementGuid>18778f15-e425-45e1-bd89-76be323a99f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0.00'])[3]/following::div[2]</value>
      <webElementGuid>090ff3d4-0217-4b90-8d0f-e8c5bfc928c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0 meses)'])[2]/following::div[2]</value>
      <webElementGuid>596af081-e0db-42a3-80ba-a20f5a778f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div</value>
      <webElementGuid>925bc6d0-7c23-4b32-b60d-5d35f0e2481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Alia Inmediato$ 700.00Ofertar' or . = 'Alia Inmediato$ 700.00Ofertar')]</value>
      <webElementGuid>fa032a74-df27-4a4d-bf01-6119ec79ddba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
