<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacin_inputIdentificacion</name>
   <tag></tag>
   <elementGuidId>1b3e4e05-559f-42a2-bf50-fc8cf7b08c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>153c7312-ffb3-4bd5-a2b4-2b39765a7bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4c36411-18fd-4d62-84a4-adb234dd7871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>85a45a29-9351-4473-8f62-6662f7d45d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputIdentificacion</value>
      <webElementGuid>2d928208-841c-487b-8429-91976418e156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese Identificación del Cliente</value>
      <webElementGuid>0ccf9dbf-ff50-444b-8a41-b5a5763781f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9007a61d-756f-4f1b-9fee-beb88a1e5705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputIdentificacion&quot;)</value>
      <webElementGuid>b04308bd-8ca8-4b5f-8c2c-d8227c44b546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputIdentificacion']</value>
      <webElementGuid>3e736b0a-10d3-421d-afc4-556a79af0917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>0795bc96-44eb-4adf-9bae-e1c141850f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>c569adea-ddaa-48c3-8452-8fd5e8b569d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputIdentificacion' and @placeholder = 'Ingrese Identificación del Cliente']</value>
      <webElementGuid>bf0344f5-03bc-4109-970c-f3f73992624a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
