<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_meses_Continuar</name>
   <tag></tag>
   <elementGuidId>7e6f5961-8806-4b21-9e1f-89ed61977d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Continuar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Continuar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ec550ac-3bab-4133-9555-be0dee58e637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/Aplica-ahora.png</value>
      <webElementGuid>df3e4cd6-4a80-46c8-bd1b-dd7398787287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bntAplicaAhora</value>
      <webElementGuid>a2549540-8e9d-422d-9930-1182cb160717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>d3d9bfb0-ded3-468e-8235-1029173c89d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Continuar&quot;)</value>
      <webElementGuid>653ddd19-c524-4bc4-a5bd-f0e46594bf7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Continuar']</value>
      <webElementGuid>fd1958ff-ba16-4265-a37f-cd05c6d237ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/div[2]/div/div[2]/div/img</value>
      <webElementGuid>ee7f65a1-8789-45b3-ac1c-5887c1ed5576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>875e9bf2-feb3-457a-9d26-3e0e8e73fd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/Aplica-ahora.png' and @id = 'Continuar']</value>
      <webElementGuid>d160321d-d842-4c91-9e98-2517ccfb30ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
