<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No es una fecha vlida_TelefonoCelular</name>
   <tag></tag>
   <elementGuidId>898b2193-4905-4e7e-b8cd-d4141ebb4504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TelefonoCelular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TelefonoCelular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e088483-73cb-49e1-a248-d468ad772877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1b966571-aa2b-4e1e-819c-814252da9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41be4cd4-0611-49b6-b78e-a8bc212dc1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TelefonoCelular field is required.</value>
      <webElementGuid>ed8ab482-c778-4732-bd9b-95db765047a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TelefonoCelular</value>
      <webElementGuid>99cd9571-fa4c-45bb-8338-3d2214016dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TelefonoCelular</value>
      <webElementGuid>91b28b9e-230c-441f-865d-bda3f7159e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>return Validarnumerocelular()</value>
      <webElementGuid>adb77750-b2b4-4a2d-8d7f-ddf9c74e66fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Teléfono celular</value>
      <webElementGuid>42c58cef-1451-48ab-ae68-67f982bef191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>01d8a73c-c898-4d05-bb3d-b52b06eb1670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>333747c1-36ec-4392-b22a-7e1beb8e6780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>78ae8e05-601c-4b1f-89ab-8e0b30e0804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TelefonoCelular&quot;)</value>
      <webElementGuid>beab4af2-958d-4d55-b89f-ff973f2a9aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TelefonoCelular']</value>
      <webElementGuid>1c479222-716e-44a3-9445-bb54ce504de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div[2]/div/input</value>
      <webElementGuid>35602c71-ba9e-4d00-aff7-41a6405dd3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>623a913a-cf95-4666-9244-9cedd4b715ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TelefonoCelular' and @name = 'TelefonoCelular' and @placeholder = 'Teléfono celular' and @type = 'tel']</value>
      <webElementGuid>8f8e74a1-49c6-4fab-953d-e7e19f74604e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
