<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Nacimiento no pertenece al cedu_1a96b4</name>
   <tag></tag>
   <elementGuidId>55823745-a949-4bce-9214-02fba055f39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FechaNacimiento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FechaNacimiento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>066aa611-27a7-45e4-ad6c-7ec69bd1b821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>52042fda-ca89-4a8d-a1b5-b2f2a0b26d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>beb74d3e-a82a-46e1-93e7-561051e5e490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field Salud must be a date.</value>
      <webElementGuid>5558f864-d45a-428a-88d4-72c55d0d7b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Fecha de Nacimiento es obligatorio</value>
      <webElementGuid>2ae32c8b-63c1-4202-a7b7-1bfc7b62bfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>06502ddd-5e5e-48d3-92b8-0e5b0487bb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FechaNacimiento</value>
      <webElementGuid>53375a0b-1fba-4d7a-a457-8db5c4e63ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>9f007ca5-95a9-4384-827f-c2411f03ba3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fecha de nacimiento dd/mm/aaaa</value>
      <webElementGuid>bb607193-02f6-4c8c-9172-c331115fa4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46ebbda7-1793-464f-81fa-be60fc56f077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/01/0001 12:00:00 a. m.</value>
      <webElementGuid>6da47d11-b983-4ffe-90f6-8f7e957eceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7098126d-6b84-44c4-914a-40bdc5709fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FechaNacimiento&quot;)</value>
      <webElementGuid>e60f84b4-a285-4d20-8e69-31ef0c450a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FechaNacimiento']</value>
      <webElementGuid>e47c1690-111d-4e7f-944e-a6ad0383bfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[6]/div/input</value>
      <webElementGuid>115b6800-ebca-48aa-8c77-0d82aa1e9d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>18f1604e-45fa-4dfb-938b-aab1a935a9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FechaNacimiento' and @name = 'FechaNacimiento' and @placeholder = 'Fecha de nacimiento dd/mm/aaaa' and @type = 'text']</value>
      <webElementGuid>ad86a8ab-2276-4729-a4bd-50c655e042f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
