<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El Correo no es vlido_Autorizacion</name>
   <tag></tag>
   <elementGuidId>33487506-2956-4677-be34-83af1bb839be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Autorizacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Autorizacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8289517-20f6-44ea-9363-950d4a5e4d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0b1e305-b5a9-419e-afac-04758bc41388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Autorizacion field is required.</value>
      <webElementGuid>c8431005-1149-47dd-85ed-6fda3cb97479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>8b7bc78c-0bc4-4173-b3ee-baa396225bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>809cbc23-432d-48c5-901d-b5faf8064f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.setCustomValidity(validity.valueMissing ? 'Por favor autorizar que sus datos sean consultados' : '');</value>
      <webElementGuid>bcae16e9-6391-4975-89df-4128753b856d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ad5510b7-bcee-439c-9ecc-251b23d492e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>139f82ac-679c-46c4-b297-3f1e5806a2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c843d977-774e-4b92-a069-cc5a7ce160eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Autorizacion&quot;)</value>
      <webElementGuid>6673e11d-4851-4059-8325-453cfb27469e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Autorizacion']</value>
      <webElementGuid>fa3f2bd5-4f2d-4016-9fea-063e62b620e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[8]/div/div/input</value>
      <webElementGuid>57c9085c-59cc-4f7b-bcd4-f915054d32b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>a930ac6a-49b0-4886-8a7e-aa5556a6d168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Autorizacion' and @name = 'Autorizacion' and @type = 'checkbox']</value>
      <webElementGuid>c6927603-8f30-4ae3-9e9b-cb61743b03d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
