<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_contrasenia</name>
   <tag></tag>
   <elementGuidId>e5b9e05b-7c69-4943-b156-bcbe4b151d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contrasenia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contrasenia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f5d4a2b-989b-4525-900c-1b52141fc249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 form-control</value>
      <webElementGuid>911aea65-1025-480d-81bb-0305c6738cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contrasenia</value>
      <webElementGuid>33a0a0a0-4d0e-4506-a57b-a91e67a4bf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contrasenia</value>
      <webElementGuid>2bad03cd-ebb3-4b56-be8c-9155cc7b55f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Clave</value>
      <webElementGuid>004b94c7-95d2-4dbe-b864-419d492bcaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>7ede7f43-a95b-45df-bbe2-733eb3463994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e738b613-6b96-4a13-8f24-f1940039b642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contrasenia&quot;)</value>
      <webElementGuid>f4b77b4a-f2db-49d0-a85b-cfec68b184a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contrasenia']</value>
      <webElementGuid>8b29cfb0-834b-4846-8ed5-a51a2195a0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[2]/div/input</value>
      <webElementGuid>12e008f4-55a0-4384-a493-efa10ebc7079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>eec6b230-6ae8-4132-a9c5-ab24ff656a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contrasenia' and @name = 'contrasenia' and @placeholder = 'Clave' and @type = 'password']</value>
      <webElementGuid>55cc87b6-45c1-477b-90a4-8b0d4ee01e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
