<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Documento Aprobado_btn btn-Solidario</name>
   <tag></tag>
   <elementGuidId>83ccb8e8-e000-4a58-975a-b9aec14394ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-Solidario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='CERRAR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>949301e3-07d7-4554-90e6-7c62a7a32a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a18aad87-157e-4150-a079-d9c15fbeb823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Solidario</value>
      <webElementGuid>b4c5b31a-3650-45e3-b61b-c20cc1ef3af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/CreditoNoCliente/GestionSolicitud/GestionSolicitud'</value>
      <webElementGuid>54280580-b312-407e-b162-99375f1d591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CERRAR</value>
      <webElementGuid>2daecdf0-8cf6-49e5-8d5e-a7623ec975d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalNotificacion&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content dialog-info&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;card-footer text-center&quot;]/input[@class=&quot;btn btn-Solidario&quot;]</value>
      <webElementGuid>e8fde630-d7c5-47ec-9562-881036d845a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='CERRAR']</value>
      <webElementGuid>07746214-ead9-4f01-9ea8-439c87ee50d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNotificacion']/div/div/div/div[4]/input</value>
      <webElementGuid>397fd9bd-b107-4393-8866-e86182a518ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>48b0026e-c803-455a-a875-1b5c644b7966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>d3ea92e0-400e-4cb9-bfe4-895c943d4ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
