<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gestin de Solicitud_dx-texteditor-input</name>
   <tag></tag>
   <elementGuidId>5e428ab5-bc79-4a55-aa50-4828d619c655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.dx-texteditor-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b3b58b9-799c-44b1-8d89-6301b1abc9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>89d1a3e4-051a-4819-a87e-79e8665b1cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-texteditor-input</value>
      <webElementGuid>2fb92564-cb2c-4dde-aa3e-f5228774fb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9db87cb4-1587-4104-9f08-ff12f3271ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6376dc1b-18e1-4d99-8245-a90f672691fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a784092a-2c4b-4dc2-ab6a-8a1561de205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9249243-5d99-462f-9a78-524240e20657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridContainer&quot;)/div[@class=&quot;dx-datagrid dx-datagrid-borders&quot;]/div[@class=&quot;dx-datagrid-header-panel&quot;]/div[@class=&quot;dx-toolbar dx-widget dx-visibility-change-handler dx-collection&quot;]/div[@class=&quot;dx-toolbar-items-container&quot;]/div[@class=&quot;dx-toolbar-after&quot;]/div[@class=&quot;dx-item dx-toolbar-item dx-toolbar-button&quot;]/div[@class=&quot;dx-item-content dx-toolbar-item-content&quot;]/div[@class=&quot;dx-datagrid-search-panel dx-textbox dx-texteditor dx-searchbox dx-show-clear-button dx-texteditor-empty dx-widget dx-state-hover dx-state-focused&quot;]/div[@class=&quot;dx-texteditor-container&quot;]/input[@class=&quot;dx-texteditor-input&quot;]</value>
      <webElementGuid>f8ad9396-d740-435a-9994-7c739841ca70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>5b54dd6e-5275-4f62-99d7-0a80132033fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridContainer']/div/div[4]/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>a4a8d31b-520d-4810-b69e-a09f21f34edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>41578cea-d0d4-4293-8acc-dea6091cccff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d7ecd01c-e48a-4d52-8f65-592e544042ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
