<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Opciones_chb144316</name>
   <tag></tag>
   <elementGuidId>20088351-4b37-4eb8-96ec-af8e021bcf68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chb144316</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chb144316']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77ddb9e5-a14e-447d-959a-892430254c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ab2b45e2-33d1-4e3e-8cd2-a77a030c81e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chb144316</value>
      <webElementGuid>f4fc3a68-8731-447c-a430-1d67fa1dc4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GuardarEstadoSeleccionar('144316','84997')</value>
      <webElementGuid>35b58562-8223-4f16-a72e-40d0c09877c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chb144316&quot;)</value>
      <webElementGuid>b6595176-18e4-4f38-a779-8f3c4c06c2e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chb144316']</value>
      <webElementGuid>f2a44738-5c32-4f28-9d49-2e703cc1b3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridContainer']/div/div[6]/div/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>e2c6b224-8757-4dbd-897d-9290e3540273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>4ca82058-756b-4ce5-9e63-7cd2987a92c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chb144316']</value>
      <webElementGuid>f8093c2b-eb04-4f71-aa5b-0991eac13155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
