<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Aprobar</name>
   <tag></tag>
   <elementGuidId>3d4850fd-251e-42ef-b4cc-a6ea538635ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnApro144316 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnApro144316']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>c212cca1-7a1f-46df-b1cb-7dd3903bfbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aprobar</value>
      <webElementGuid>9ac36fa4-1bdd-43f4-9779-3d546dc1507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnApro144316&quot;)/strong[1]</value>
      <webElementGuid>657d8417-5ad2-46cc-b1a1-fe322876312b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnApro144316']/strong</value>
      <webElementGuid>098a3485-5219-4549-9b14-1cfcd9ec811f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Documento'])[1]/following::strong[1]</value>
      <webElementGuid>8854e6be-e8fd-43a8-9401-ecc14bdd343f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Negar'])[1]/preceding::strong[1]</value>
      <webElementGuid>a25890ce-d63b-49e6-861b-8cda0d37c32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::strong[2]</value>
      <webElementGuid>c4b7cb3f-bba1-483f-818d-c37028a88996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aprobar']/parent::*</value>
      <webElementGuid>1895f792-3494-4129-919f-a53e0589be22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/strong</value>
      <webElementGuid>a6d391c2-9ddb-4017-906c-a1b201ba95f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Aprobar' or . = 'Aprobar')]</value>
      <webElementGuid>baa91e52-ccb9-40e9-8d79-5578121f1a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
