<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ofertar</name>
   <tag></tag>
   <elementGuidId>72f456b2-dc88-4cfd-9357-3357a29baaec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.info-box-number > span > button.btn.btn-success.oferta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[23]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd13d603-3c50-4b0b-8bac-0f47c6a09678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>447b4d8e-088d-40e1-a10b-e8af81a58726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success oferta</value>
      <webElementGuid>11c2e012-9d82-4255-925b-712a3d3150fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PresentarOfertasGeneradas('Alia Inmediato', null, null, null, 1200.00, 'ALIINM', true);</value>
      <webElementGuid>f9b14c17-72d2-4eb0-a48b-a24c8833b91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe1edb8c-53c5-4090-8432-1f2613627b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ofertar</value>
      <webElementGuid>c16b6e39-2873-4d4b-972c-50e5205aa628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementosOfertas&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;box box-default&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;info-box&quot;]/div[@class=&quot;info-box-content&quot;]/div[@class=&quot;info-box-number&quot;]/span[1]/button[@class=&quot;btn btn-success oferta&quot;]</value>
      <webElementGuid>28b4619f-cf26-4fa7-82d8-67a25544e2c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>87b4284b-9f40-4f04-8e5a-6fb649f5d8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementosOfertas']/div[3]/div/div[2]/div/div/div/span/button</value>
      <webElementGuid>0b3cf11d-725e-478f-aa70-0008bf2ad833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1200.00'])[1]/following::button[1]</value>
      <webElementGuid>b16ae2da-6869-4fe7-ab28-4a140e80c733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alia Inmediato'])[1]/following::button[2]</value>
      <webElementGuid>8de4bfc6-f9ad-4981-b3a4-d2b988ecd2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UniCrédito Análisis'])[1]/preceding::button[1]</value>
      <webElementGuid>34077491-da5b-4b4d-ba48-485be2dd4922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/button</value>
      <webElementGuid>d2dd611e-183f-41bb-8384-d4a11348d454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ofertar' or . = 'Ofertar')]</value>
      <webElementGuid>31dd319e-aeec-46bb-b026-441a51993958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
