<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Campaa</name>
   <tag></tag>
   <elementGuidId>3730c2a1-59d9-4e70-8e7c-0e384d151331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPresentarOfertasBotonConfirmacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f42b30c8-d48d-4468-9f44-cea8228f288e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5019d5f8-6261-4dd9-ae71-6eea88284bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPresentarOfertasBotonConfirmacion</value>
      <webElementGuid>48b174f6-65f8-47a8-8bca-171c739f1572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e67efaeb-02f0-4b20-9f20-b74a49c3f830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78884031-d8bb-48be-aaac-f952a59f649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Campaña</value>
      <webElementGuid>76d7f666-066b-4cb8-a5aa-adc2ecb8e337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPresentarOfertasBotonConfirmacion&quot;)</value>
      <webElementGuid>4ef4fc8b-6ba1-4b92-a423-8e5bdfb0fcf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPresentarOfertasBotonConfirmacion']</value>
      <webElementGuid>576c917b-933b-43ae-b167-c84988a1a47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPresentarOfertas']/div/div/div[3]/button[2]</value>
      <webElementGuid>0e4d959f-57bc-43b6-85b9-510a1894f623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::button[1]</value>
      <webElementGuid>cb57db52-db88-4241-b040-6458f259fa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1200.00'])[1]/following::button[2]</value>
      <webElementGuid>1cd0229e-010f-4069-a0b4-e218cecd0aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofertas Generadas'])[1]/preceding::button[2]</value>
      <webElementGuid>16e54018-1b56-41a8-ac2e-0c29e4397dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Generación'])[1]/preceding::button[2]</value>
      <webElementGuid>259a1b2e-1da7-45fa-be3e-120799222fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Campaña']/parent::*</value>
      <webElementGuid>ba91c0db-c3e6-4d0d-8e7e-0c53de5aee0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/button[2]</value>
      <webElementGuid>14be97af-3cf5-47f9-a887-59d7d1e9ae14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'modalPresentarOfertasBotonConfirmacion' and (text() = 'Generar Campaña' or . = 'Generar Campaña')]</value>
      <webElementGuid>f55fb97d-379a-402a-afd9-2fb52bfbe3b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
