<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacin_inputIdentificacion</name>
   <tag></tag>
   <elementGuidId>4670fa9e-4093-4126-9c1b-d73ed29eba81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b7e253c-2d54-4485-931a-e2da1b61c6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f37e65a1-c190-4920-b06f-95738e3201e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>74161df3-f8e4-4a04-b9f6-936402c5cff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputIdentificacion</value>
      <webElementGuid>c14ad733-a992-456c-ab04-27739556d044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese Identificación del Cliente</value>
      <webElementGuid>6bad0899-0aee-4536-a81d-b16280599f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f6cc3198-f5ac-470a-b3b3-ed5538b2334e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputIdentificacion&quot;)</value>
      <webElementGuid>2a3d99ad-1b28-4c46-a607-196f1e670e28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputIdentificacion']</value>
      <webElementGuid>2c46224b-d64a-4df5-abf5-61361b39ee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>e432b567-42ce-4674-8583-2748ba2ea447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>3b62fef3-4c26-4188-84b4-a5a19bffd01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputIdentificacion' and @placeholder = 'Ingrese Identificación del Cliente']</value>
      <webElementGuid>4fb653d4-86b7-40c7-90a9-d2e5a3f47a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
