<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>faecc4b6-281f-4f13-b97f-51bf878c5b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalDocumentoGeneradoCerrar > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalDocumentoGeneradoCerrar']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e633f307-b1aa-49ac-8bf8-82d1b539e016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae450a38-3a18-4cb2-9eaa-d8c3470f680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>708a74a1-8a01-48af-bb6e-0e8062d14378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDocumentoGeneradoCerrar&quot;)/span[1]</value>
      <webElementGuid>450bf7f1-68ba-4ce0-ab40-104f30aa546a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='modalDocumentoGeneradoCerrar']/span</value>
      <webElementGuid>75b38152-4aed-450c-9a35-886c366f0342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oferta'])[1]/following::span[1]</value>
      <webElementGuid>61140580-efa4-49ab-bd71-4e138ace08c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secuencial'])[1]/following::span[1]</value>
      <webElementGuid>c15f130b-cf1e-4494-a1f8-c03e96a2667e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documento'])[1]/preceding::span[1]</value>
      <webElementGuid>eecf31c8-7e87-4fe1-8251-6e655ec1cdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Internos'])[1]/preceding::span[2]</value>
      <webElementGuid>f3199437-7060-4ae1-a797-a5640c9648d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button/span</value>
      <webElementGuid>d469515f-a2f5-4c45-8da2-9fe01faad2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>77379849-c0a7-49c7-91c7-33bb9c566620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
