<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oficina_btn btn-primary</name>
   <tag></tag>
   <elementGuidId>cbcd085a-946c-40b2-b867-bc3d32a5cf04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Ingresar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12a97e84-404b-4074-868d-36a8274542a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c32f31f-511d-4716-aa4a-595e302d4e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Autenticar();</value>
      <webElementGuid>bae1a468-a027-42c2-8cb6-4c4eb23f3179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>7419c740-42d4-46c0-93c8-3dc43496e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>56331aa9-3854-4844-8e86-07c09d5bd227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-3 col-md-5 col-md-offset-4 col-lg-4 col-lg-offset-4&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12 controls text-center&quot;]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>67b37459-b7e9-4267-9c21-897a4a77016d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Ingresar']</value>
      <webElementGuid>3ea09c23-8aa7-4b9f-b678-81fd3a745779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section2']/div/div/div/div[3]/div/input</value>
      <webElementGuid>32fa7a54-cbf0-45f8-a51d-7cbb5aea47f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>baaa48de-12b5-4db3-acae-238c6e3fd76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>de9386a8-78a0-48f9-b868-429a5dbcdf44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
