<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero_Numero</name>
   <tag></tag>
   <elementGuidId>e957bbce-b98a-48db-ac1a-80233bcacd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Numero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Numero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>578220f0-aa5e-4135-9460-e6e5f048520e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control labelGLNegro labelTamanio</value>
      <webElementGuid>bcc93b99-7fed-4413-bcdb-ccb8c20dc49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8749dd02-f2a2-4b68-9f1a-ee260921c594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Numero field is required.</value>
      <webElementGuid>464ed2d3-0f57-459f-980a-2652e82ca8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Numero</value>
      <webElementGuid>9ec48d5a-702c-4e37-baca-838bb8270ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Numero</value>
      <webElementGuid>ff85b830-f0ec-42f2-ada3-c10c688f2465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>5017d474-6fc1-431a-87b4-a870b71ba06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>setCustomValidity('Ingrese el Número de la Empresa.')</value>
      <webElementGuid>4e13f2a5-7eb8-41a8-a58a-3e5054a945af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b1d6842-f1a0-41e7-828d-0335ba7ff9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Numero&quot;)</value>
      <webElementGuid>fa2a36d0-44b8-437a-8a96-d5b647899c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>4ab81d78-96d3-45bc-839e-4be693e1f676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Numero']</value>
      <webElementGuid>d7a38765-5085-4a9a-ae98-0a2903838e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div/div[4]/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>9e58fce6-a699-4257-8b33-a7951b503d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>7b3b3349-aabe-4e21-8ddf-12a1c9a7b45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Numero' and @name = 'Numero' and @type = 'text']</value>
      <webElementGuid>5136c193-5ece-4469-9b64-6e7216a2dad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
