<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GasServiciobasico</name>
   <tag></tag>
   <elementGuidId>81baf8e5-b634-425c-8036-e8ae37469ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasServiciobasico']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasServiciobasico</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3ac1152-7c5d-4541-8cd1-a0cfa1553e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>c994c2f1-3348-4451-9d9b-42447382a216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmtallocated pull-right</value>
      <webElementGuid>fbce75ba-0442-4c67-93f2-d54ff5c9978b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>908c9b04-004f-46cf-8443-2164d029413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field GasServiciobasico must be a number.</value>
      <webElementGuid>7f1e0154-9981-410a-8eff-8bfbb09c9f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GasServiciobasico field is required.</value>
      <webElementGuid>b8a3df76-f924-4386-8d8a-f430f453a7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasServiciobasico</value>
      <webElementGuid>712c75d8-43a1-49b5-b1af-f92cb1db118e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasServiciobasico</value>
      <webElementGuid>a3b718b9-8a03-4d0b-95d5-deb756b498e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calcularGas();</value>
      <webElementGuid>e473539c-13b2-48ba-b4a9-bcb1640f726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('GasServiciobasico')</value>
      <webElementGuid>fc84ca15-83e2-4ba0-912c-a05a756b382c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>29697d86-8b38-45d6-9123-a64d0fe43795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'GasServiciobasico');</value>
      <webElementGuid>3a5c3b71-b4e0-4dcb-8c41-7decbb7a2854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba4dc2e6-16ff-495c-a9c3-6e65c4cd8ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38352d90-f9ac-437c-b937-c4bfb9e464ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasServiciobasico&quot;)</value>
      <webElementGuid>711ccee7-75e8-48dd-bb4f-faac58a5b991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>d3724c8c-324b-4357-806d-780325761cf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasServiciobasico']</value>
      <webElementGuid>d9b74e10-52cc-4f55-baea-a87a74359b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div[2]/div[5]/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>97857bc1-2d5f-468e-91ab-b05528c200c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bef2e7cc-fa11-411d-bbe0-8cedc91b8c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasServiciobasico' and @name = 'GasServiciobasico' and @type = 'text']</value>
      <webElementGuid>1d94ee3d-5e5d-4eb6-b5d4-613bb5cf1317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
