<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__GasOtros</name>
   <tag></tag>
   <elementGuidId>7fa49988-ad05-45a9-b540-06e93e9893bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasOtros']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasOtros</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6277dc96-22b5-4cbd-b778-b670ba0c64cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>4e865885-9353-42ee-b5ef-eafe7cf4972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pmtallocated pull-right</value>
      <webElementGuid>f32ec9f1-2125-4b81-a555-67c641c4729e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1997c09f-2c59-40ed-8466-5c026b09a268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field GasOtros must be a number.</value>
      <webElementGuid>2a9bd89d-58ff-4646-8f61-515c7f2cfb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GasOtros field is required.</value>
      <webElementGuid>01f00a27-72cd-4857-8eac-574c6860c66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasOtros</value>
      <webElementGuid>c797dce3-8235-4ae6-91f6-fccdd2d91270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasOtros</value>
      <webElementGuid>10fcd049-17b9-4f4e-848d-a138d1471b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calcularGas();</value>
      <webElementGuid>b8aac7f8-cf78-4c18-9148-8e3b1391827f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('GasOtros')</value>
      <webElementGuid>9715e12f-06e7-43f5-b2f1-84f63187a930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>7f9371d4-80c1-4c0e-b4a9-5838e5898b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'GasOtros');</value>
      <webElementGuid>64b90c65-59a8-4105-b5a3-440313875674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f99e3514-9a21-4ed6-8219-f86b5dac4c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17c10962-7039-48b3-b27f-d497b7f0e2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasOtros&quot;)</value>
      <webElementGuid>74a9ebda-b801-4f91-bc11-1f51578d0762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>4f229ce6-3648-460c-9355-9051d5973d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasOtros']</value>
      <webElementGuid>eb7648d9-c559-4c84-9f6f-cbf0970c0dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div[2]/div[5]/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>33468821-67c1-4ac6-924b-8f557fddd286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4cf6dff0-e5f3-4a10-b587-17527e7457b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasOtros' and @name = 'GasOtros' and @type = 'text']</value>
      <webElementGuid>95670435-5c3b-4598-b857-e93d9645c4c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
