<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Debers realizar tu pago todos los mes_fca271</name>
   <tag></tag>
   <elementGuidId>81e9327d-35d1-4428-8c54-f0ea0bf47008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnContinuar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnContinuar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52dad5f4-2f76-406f-8c86-1f623f08bddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d90b95be-9e69-44ae-93f2-d425639cef63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnContinuar</value>
      <webElementGuid>02bb5933-f223-41ec-a794-2643ef7f792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinuar</value>
      <webElementGuid>27b286d2-130d-4a63-833c-428260b89dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonContinuarSolidario</value>
      <webElementGuid>eb2c3118-a6da-4bf1-a3f3-dee5a3f02f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SetearDireccionFlujo('C');</value>
      <webElementGuid>c4cdafc6-c804-4aef-afb4-4f769a014a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinuar&quot;)</value>
      <webElementGuid>dbb2267d-eb59-4629-bd24-1fa3275251f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>b97cfb0e-d41a-4bd1-b8ce-fe4620211fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnContinuar']</value>
      <webElementGuid>1f3ef355-c8bd-4f64-aed7-d5e9032830af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div/div[4]/div/input</value>
      <webElementGuid>1a124b30-05ee-4072-9ae4-290cbcc0b637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>021a3353-779d-432a-839f-fcdfffaa0c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnContinuar' and @id = 'btnContinuar']</value>
      <webElementGuid>2e01e38c-aa21-4762-9f40-b4357cfd5e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
