<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TotalIngresos</name>
   <tag></tag>
   <elementGuidId>7926238e-b131-4b0e-81f4-888cc04211ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TotalIngresos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TotalIngresos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96159dc3-0506-42bf-9168-44ddf609e276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>94a23901-bf46-4599-ab64-8230bc8c0740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>labelGLNegro resizedTextbox</value>
      <webElementGuid>02c848f1-c834-49c8-9188-7c8e806fbf11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca06cf04-f07e-4b53-ad7c-580d7cd1a282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field TotalIngresos must be a number.</value>
      <webElementGuid>5ee6d7e8-d238-4975-b0dc-d23799039159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TotalIngresos field is required.</value>
      <webElementGuid>f43d17e6-d93d-48f8-8574-c3baa7def2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TotalIngresos</value>
      <webElementGuid>cb7c5f06-3691-417a-aede-f4fd4b8203b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TotalIngresos</value>
      <webElementGuid>6057a9bd-bca0-4b83-8cf7-0749bfa1e74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onChangeDecimal('TotalIngresos')</value>
      <webElementGuid>dfe2a26b-8aeb-42e0-a6d6-89f007bbb6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>Mayoresacero(this);</value>
      <webElementGuid>cfe92da4-f0d1-417d-8835-a19b0a27c68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return Mayoresacero(this);</value>
      <webElementGuid>548156b2-7735-4d94-bfce-2c65080d2ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>MascaraMoneda(this,event,'TotalIngresos');</value>
      <webElementGuid>46998a88-75e9-4271-b12f-cba38da34e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validadifSinCero(this)</value>
      <webElementGuid>5f34ce4d-b4ec-45ca-abe9-b7596fad5eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7099b2a-bae9-46ab-ba12-e6982285e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43b923e4-81d3-496b-8082-35e8c502fb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TotalIngresos&quot;)</value>
      <webElementGuid>9c474293-87a4-472d-a0db-48b9f4837cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>7a0c89a2-f44d-4cfa-adc0-9164d4630590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TotalIngresos']</value>
      <webElementGuid>71241db4-97b3-44fa-bc0d-8334cd6acff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div/div/div/div[2]/input</value>
      <webElementGuid>c1750c36-cf51-46e4-a685-be13b0f11638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a41cc394-d58a-44ea-b472-680be1383bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TotalIngresos' and @name = 'TotalIngresos' and @type = 'text']</value>
      <webElementGuid>29c5a273-6994-4c93-9807-52c26bebb91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
