<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__checkmark1</name>
   <tag></tag>
   <elementGuidId>78cae599-0768-4e6d-8887-57afa6cc884c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global']/form/div/div[4]/div/div[2]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-1.col-md-1.col-sm-1.col.col-xs-2 > label.containerI > span.checkmark1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f3d6b3e-a8e9-44d0-9e8f-4d3c64d1f87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark1</value>
      <webElementGuid>58978a9e-73c0-4118-825c-d50cbc3eb932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global&quot;)/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;containerPrincipal&quot;]/div[@class=&quot;row labelGLNegro&quot;]/div[@class=&quot;panel-info panel espacio text-justify&quot;]/div[@class=&quot;row espacio&quot;]/div[@class=&quot;col-lg-1 col-md-1 col-sm-1 col col-xs-2&quot;]/label[@class=&quot;containerI&quot;]/span[@class=&quot;checkmark1&quot;]</value>
      <webElementGuid>20e53a44-d26e-457c-99aa-15a2e8b72efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Rapiditos Clientes/Flujo Clientes/Page_Crditos/iframe</value>
      <webElementGuid>24107093-a443-4b32-8b27-cdc1792cccaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global']/form/div/div[4]/div/div[2]/div/label/span</value>
      <webElementGuid>fe116382-86fb-4ef5-b450-bf2a7ebccd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/span</value>
      <webElementGuid>2c3c0588-2ec5-4a7b-8ebd-631eba962f2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
