<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crditos</name>
   <tag></tag>
   <elementGuidId>15c869e6-29dd-4da5-b5f7-cd61c2447844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Créditos')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-tab-link.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83205858-d5ae-42ae-9cc7-5b79a3739304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-link ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>2ab598a0-aa68-4775-8adb-2f4d11073836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b4b5a39-91f8-43cf-a171-d81b6fdc13c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d50f97b-a346-4154-a7ef-09f6c1967944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Créditos</value>
      <webElementGuid>801a2144-c783-4a5c-82df-2aecf0eebab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;level2 ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;level2__content pt-3&quot;]/nav[@class=&quot;mat-tab-nav-bar mat-tab-header mat-tab-header-pagination-controls-enabled mat-primary&quot;]/div[@class=&quot;mat-tab-link-container&quot;]/div[@class=&quot;mat-tab-list&quot;]/div[@class=&quot;mat-tab-links&quot;]/a[@class=&quot;mat-tab-link ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>20b2b650-9100-4ca9-8596-5b63ad59922f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Créditos')]</value>
      <webElementGuid>64421a4a-dc8a-4b71-80be-b12dae588e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos y transferencias'])[1]/following::a[1]</value>
      <webElementGuid>00c83e30-180f-433a-9c8a-b2b7fa4a50da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjetas ALIA'])[1]/following::a[2]</value>
      <webElementGuid>5f7fb1d5-868a-48ff-8d30-844e2e981cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas'])[1]/preceding::a[1]</value>
      <webElementGuid>b55245b6-0e79-40e3-87e9-b76e0d80f4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billetera móvil'])[1]/preceding::a[2]</value>
      <webElementGuid>579a3c87-2cfc-4c2d-a434-d44f5d1313a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Créditos']/parent::*</value>
      <webElementGuid>41b92f0c-117f-46c1-87b1-b1ad19b0d5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>f717e81c-d5d3-4ff2-bab8-1ba742b68d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Créditos' or . = 'Créditos')]</value>
      <webElementGuid>613508c6-49c5-4b20-aa45-03940b039f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
