<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oficina_btn btn-primary (1)</name>
   <tag></tag>
   <elementGuidId>b8631b06-21b6-4a53-a605-70e5f0c46917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Ingresar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adee5438-3cdf-42d7-880b-5397704eae8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa73e4fe-84a2-4c32-abca-95ffcde80a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Autenticar();</value>
      <webElementGuid>04aa9140-8163-4f93-a4ef-f5ffcedbcfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>ac2cf535-856d-4a0f-81fb-0eadad789c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8e39c568-a514-4629-8612-96c98b383dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section2&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-10 col-xs-offset-1 col-sm-7 col-sm-offset-3 col-md-5 col-md-offset-4 col-lg-4 col-lg-offset-4&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12 controls text-center&quot;]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>d01bc7e3-a8cb-4a26-80f6-d2d5dd1467d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Ingresar']</value>
      <webElementGuid>1af4eed7-76b6-4e97-be3b-e41d283d8024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section2']/div/div/div/div[3]/div/input</value>
      <webElementGuid>23b75136-e5a0-40ac-9412-39dbbe34b7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>204024a9-60fd-424c-bbae-8be6476ba49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>fa9b8cd3-3708-448a-a30c-75dc3d92907e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
