<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buscar</name>
   <tag></tag>
   <elementGuidId>f5b23d16-0dd8-4627-80e5-21c527939f75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonBuscarCliente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonBuscarCliente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5e6b16d-e4a0-40d7-a26c-41056ab4bf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bc9049b-9fa2-4998-be3d-f38807a67b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonBuscarCliente</value>
      <webElementGuid>16460963-0168-42af-a6f5-e555cbb14e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>5e8d68a6-eacc-4a6a-af76-00e369917baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>768b30f2-ab10-46ca-9510-c6fd464a3b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>368247d6-d17a-44b2-979d-3352644d68c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonBuscarCliente&quot;)</value>
      <webElementGuid>f8b8a062-fd00-4ac2-ac0f-810cf516b9a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonBuscarCliente']</value>
      <webElementGuid>2280fc86-a119-4f6e-bcfd-ff4e715eea30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div[2]/button</value>
      <webElementGuid>59999d6b-d0e4-44ff-be61-80c24d9d0a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identificación:'])[1]/following::button[1]</value>
      <webElementGuid>0bc3c7f2-aa47-4ad3-bb87-6dab50fde02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Cliente'])[1]/following::button[1]</value>
      <webElementGuid>0d74164c-66da-4012-8665-85e81ee25cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/preceding::button[1]</value>
      <webElementGuid>033a8d27-7b9c-4f9d-bca4-215e8153f3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reimprimir Oferta'])[1]/preceding::button[2]</value>
      <webElementGuid>bdd04985-edc1-4497-bcab-38faf50c8bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>4f11eafa-35c3-464d-8608-fdc934582a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>2c5761a5-cf52-41c3-a0ce-ccba10309249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonBuscarCliente' and (text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>d33644cf-a667-4390-a4de-a6c04dcaadbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
