<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identificacin_inputIdentificacion</name>
   <tag></tag>
   <elementGuidId>b387d958-4233-4d17-a2a8-5ee255f7db1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b61e4e0-55ef-444c-a81b-c8fcff2c5c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b074622b-6f87-47a5-8478-c3a40818b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86533eea-1e80-4d77-a633-47be87bf993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputIdentificacion</value>
      <webElementGuid>e31043b8-5096-4d62-91df-7d7f917b4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese Identificación del Cliente</value>
      <webElementGuid>725496b5-889b-460b-98bd-4930ebfad4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c24a02f0-8a8d-4ce2-8579-905e30a9ce56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputIdentificacion&quot;)</value>
      <webElementGuid>4b37c1c8-903c-4716-b01d-e541da5c23bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputIdentificacion']</value>
      <webElementGuid>4525301d-2efd-4ff0-a360-6b30d898c932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Formulario']/div[7]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a5b8b571-ebc1-4055-b828-0fefe3bf91c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>db985277-bea4-47e8-8f10-93e04f0de297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputIdentificacion' and @placeholder = 'Ingrese Identificación del Cliente']</value>
      <webElementGuid>786a8a59-2ffc-4be2-89d7-3d1b12eb529f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
