<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crditos</name>
   <tag></tag>
   <elementGuidId>995ef1a2-25ee-4209-a0b8-6a38d2c41600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Créditos')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-tab-link.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c6aa876-b593-466d-be11-e1133fda532e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-link ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>417a7c29-1de6-413c-9196-88b9b4c6fb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46ba0ae1-654a-4ed8-a011-a78b825f73a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99ed7254-494e-418a-b4e9-65e74e179ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Créditos</value>
      <webElementGuid>e2607032-37c8-45a5-8d1b-2c32b0467154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;level2 ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;level2__content pt-3&quot;]/nav[@class=&quot;mat-tab-nav-bar mat-tab-header mat-tab-header-pagination-controls-enabled mat-primary&quot;]/div[@class=&quot;mat-tab-link-container&quot;]/div[@class=&quot;mat-tab-list&quot;]/div[@class=&quot;mat-tab-links&quot;]/a[@class=&quot;mat-tab-link ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>197b440e-9c56-4037-96f0-d799ae6113ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Créditos')]</value>
      <webElementGuid>7ba603fb-776b-4afd-932f-07dca78c5c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos y transferencias'])[1]/following::a[1]</value>
      <webElementGuid>fc60e73b-4117-471a-8165-72e69d95bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjetas ALIA'])[1]/following::a[2]</value>
      <webElementGuid>be62c1ae-fc99-41aa-8b55-7de8ca2dec43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas'])[1]/preceding::a[1]</value>
      <webElementGuid>58a0a63f-0f7a-4894-9f1b-d85f02286ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billetera móvil'])[1]/preceding::a[2]</value>
      <webElementGuid>0341ef77-1a06-4d69-9b69-b119701df5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Créditos']/parent::*</value>
      <webElementGuid>d1b33887-45d9-44f4-abf3-3e60e92ba051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>3cc2cd7a-5cd4-4c1d-a3df-c649724995bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Créditos' or . = 'Créditos')]</value>
      <webElementGuid>160a6e62-5b78-4023-b26d-68f93cc439b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
