<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El Correo no es vlido_Autorizacion</name>
   <tag></tag>
   <elementGuidId>bc8e6ca1-5e1d-46ec-a060-0707fa60e3e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Autorizacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Autorizacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f606689-630a-4d46-b4d9-62804641de11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57f603d0-6104-480a-9d55-c8f01bd4360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Autorizacion field is required.</value>
      <webElementGuid>c824cd0b-ea6f-489a-abf0-36c6a8278503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>ffedcd27-185c-455d-aefd-2ef4062a3f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Autorizacion</value>
      <webElementGuid>ce36277e-f285-4562-a53c-3a4b4c7bd7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.setCustomValidity(validity.valueMissing ? 'Por favor autorizar que sus datos sean consultados' : '');</value>
      <webElementGuid>64f399d8-fea4-4f1c-9a95-3f005544f714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>61d7d8ff-bcc7-43f1-a535-6f9957cc50e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dcf37d9b-cbdc-430b-8244-ef84a2d76813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30ba8713-e780-40fa-96d4-c2f294f24c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Autorizacion&quot;)</value>
      <webElementGuid>635ef1be-f77a-4802-8fcb-d2652072b7e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Autorizacion']</value>
      <webElementGuid>b33737b3-4cdb-4618-9dd0-fbcc8118ae9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[8]/div/div/input</value>
      <webElementGuid>1fe4d83f-df1a-43cd-a4ce-e37adc350e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>fdf296a7-a58a-406e-9eb4-058267a0f030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Autorizacion' and @name = 'Autorizacion' and @type = 'checkbox']</value>
      <webElementGuid>9406fb51-e285-4b0e-8a9c-a274282e049b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
