<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VER TUTORIAL_btnContinuar</name>
   <tag></tag>
   <elementGuidId>a0cd7eab-ecd5-4c98-bd9b-8f4b95f4d33a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnContinuar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnContinuar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8dd0799-18d1-4ddd-af19-60ff9a36f827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>79f5d4e8-205d-4ec5-bcc0-0f67c9c30f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>fdf58093-dcf4-4328-93e7-5f90d9645be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnContinuar</value>
      <webElementGuid>551b84cc-fb28-4910-a5aa-6162ecbc85f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinuar</value>
      <webElementGuid>e2f38f23-e752-446f-8268-0606b73fd22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-Solidario</value>
      <webElementGuid>7ff5d280-50ed-446d-8429-e0bf538472a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinuar&quot;)</value>
      <webElementGuid>55fda506-3e4a-499c-957d-04680cda451c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnContinuar']</value>
      <webElementGuid>6fdeb6fe-e880-4e65-b547-4a4b177f4bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[9]/div/input</value>
      <webElementGuid>f1647f74-f0cb-46d4-9ca5-bb95ce5f3eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>9c313ed7-d3d9-452e-a05d-8c7ba85ffee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnContinuar' and @id = 'btnContinuar']</value>
      <webElementGuid>137bd719-0b5e-4584-bbdc-049d532f7443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
