<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vamos a empezar, ingresa los siguient_c53a2e</name>
   <tag></tag>
   <elementGuidId>f9bb4ebf-abc5-41f2-ab09-8b57161366c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identificacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Identificacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38548cb6-c40f-403a-9f87-cb6b95316bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bbb06518-75fd-4c8b-88a5-3507f0dc4f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b842e44-73f5-44a2-8366-3fe1ecfd200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Identificacion field is required.</value>
      <webElementGuid>269e74e4-a77a-4c20-a715-ae234ec42aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identificacion</value>
      <webElementGuid>e5f376e8-3f19-4d7b-9ed8-db267fca301b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>89277793-0891-424e-b452-10497159b289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Identificacion</value>
      <webElementGuid>9b32dca7-ab0d-462b-8ad4-e5dacd378dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>setCustomValidity('')</value>
      <webElementGuid>72085ab6-473c-4951-845f-c5003b12a230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return numericOnly(this,event)</value>
      <webElementGuid>a106d31e-2388-4794-b77d-98cb45120abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cédula</value>
      <webElementGuid>29058e1c-1162-4c25-bc6f-4df63d4f7397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>75ad3567-2aae-487c-b755-e37a48886dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc088a0f-edd9-47de-b305-7b82663684b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identificacion&quot;)</value>
      <webElementGuid>ec7a45cb-ec5d-45d0-a9b5-11ebc6428348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identificacion']</value>
      <webElementGuid>89c219cf-2f04-4705-af91-534d42952953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmGrabarOperacionInicial']/div/div[5]/div[3]/input</value>
      <webElementGuid>c551c8b5-6e78-4e6a-8ed8-ce6bb5258ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>280a142e-6ed2-4844-89af-f89dc743a076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identificacion' and @name = 'Identificacion' and @placeholder = 'Cédula' and @type = 'text']</value>
      <webElementGuid>9be2b582-a34f-45d2-9de9-6cf4d9343e8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
