<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_meses_Continuar</name>
   <tag></tag>
   <elementGuidId>b0a96c6d-9f6b-4176-9a89-4742b3508b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Continuar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Continuar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f2632f7c-89c6-44cb-bd77-531de38f628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Rapidito/Solidario/Images/Aplica-ahora.png</value>
      <webElementGuid>f8c7ba96-753a-4d0e-94ac-74b30d94996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bntAplicaAhora</value>
      <webElementGuid>4fcfefcb-d0b8-432a-b206-2b90218d06ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>51233c9f-ceb7-4ba9-b284-be2a4bd37262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Continuar&quot;)</value>
      <webElementGuid>78529db1-fd86-468b-85ae-534757b555bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Continuar']</value>
      <webElementGuid>ee9ad55f-7afd-496a-b791-e03bdafdf18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/div[2]/div/div[2]/div/img</value>
      <webElementGuid>84b0c9e3-05bc-471d-bf15-cd41ac05b256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>e15bab5d-6625-47ec-b489-3d48c87cb3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Rapidito/Solidario/Images/Aplica-ahora.png' and @id = 'Continuar']</value>
      <webElementGuid>c9758aac-ea81-4312-8d1c-a50f867d396c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
