<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>35971a14-1e84-4e80-b87d-741807989607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bloquea1']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d54ca20a-8848-4098-b7cc-07297f88cfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3a8cc406-a938-4d46-8c9f-cc2025445d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4240cf69-3613-43e1-a607-9a808a2e74ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CreditoWeb/Solidario/ImagesMicrocredito/ACEPTAR_xs.png</value>
      <webElementGuid>dec8aafe-b7ba-460f-9c17-d0b46bc9d487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bloquea1&quot;)/div[@class=&quot;dialog-card&quot;]/div[2]/img[1]</value>
      <webElementGuid>84caab2c-db74-4c4c-a6a2-95cd4b47c1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MicroWeb Flujo Normal Ok/Page_Resumen/iframe</value>
      <webElementGuid>4cc66d3c-c26a-4945-91c2-b0cf591e983d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bloquea1']/div/div[2]/img</value>
      <webElementGuid>647950a0-b902-47e9-9112-3bd8bc75dc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/img</value>
      <webElementGuid>e1711e42-719d-4c3a-9257-0a4c1365abdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/CreditoWeb/Solidario/ImagesMicrocredito/ACEPTAR_xs.png']</value>
      <webElementGuid>3de739aa-8a62-4496-a3f6-305191f6e697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
