<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gracias por confiar en Banco Solidari_92ad5e</name>
   <tag></tag>
   <elementGuidId>46fe0f42-600f-4218-ba27-2d2e9b7d2f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnCerrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnCerrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ba72591-38ff-490c-8f2c-ee32908df143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>818720c9-1e09-49fa-b6f9-5d9e24942c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnCerrar</value>
      <webElementGuid>0da7832f-327f-4fb7-b532-f3c76394c634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCerrar</value>
      <webElementGuid>ac1711a4-cb48-442c-8267-69e8fbfb77b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonCerrarSolidario</value>
      <webElementGuid>702bd1b7-78cc-4c70-ad04-285e525e7439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RedireccionaPosicionConsolidada();</value>
      <webElementGuid>7a0b37ee-0606-4dcf-8408-874e514870a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCerrar&quot;)</value>
      <webElementGuid>e56511f1-4eef-469f-b254-2ac412d0d7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MicroWeb Flujo Normal Ok/Page_Resumen/iframe</value>
      <webElementGuid>93b5ed4a-03a8-4e27-9e92-92d7c8f8e379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnCerrar']</value>
      <webElementGuid>2872bb9d-6560-41e3-bdd4-3e8f10a5b7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f2438a62-2398-447f-8c31-87d117a8b7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnCerrar' and @id = 'btnCerrar']</value>
      <webElementGuid>7d7972bb-2903-4ecf-acd4-d7cbf355088f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
