<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cundo deseas pagar tu primera cuota_b_d16ea4</name>
   <tag></tag>
   <elementGuidId>6aaa5e9c-0848-4b5a-a7ce-0b8fbad5f3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnContinuarSolidario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnContinuarSolidario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e6d5fc0-8294-477a-ad53-89ff4da0e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1340265c-63c2-4aa1-9f33-2f28b971f238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnContinuarSolidario</value>
      <webElementGuid>22ecf2de-7c78-4184-9e1e-f27e63562e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnContinuarSolidario</value>
      <webElementGuid>d5332fc5-cb52-46c5-8fc6-bcdae17bacc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonContinuarSolidario</value>
      <webElementGuid>c996fc28-3997-434b-865f-98dadfb32292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnContinuarSolidario&quot;)</value>
      <webElementGuid>6da5ca3e-e2ce-42ba-9800-60e1101dba83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MicroWeb Flujo Normal Ok/Page_Resumen/iframe</value>
      <webElementGuid>05356882-07ed-445b-808a-5fac65bed2a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnContinuarSolidario']</value>
      <webElementGuid>c4c76fb1-07dc-4c42-b365-388974549544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[2]/div[5]/div/input</value>
      <webElementGuid>51a39500-b61c-42f7-8c19-1b5ff7d807c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>2b317211-4a6e-44d6-b3b1-36c69773469f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnContinuarSolidario' and @id = 'btnContinuarSolidario']</value>
      <webElementGuid>08db89a2-e633-4879-88fe-ae5f56be5c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
