<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Costo mensual del seguro_btnAceptar</name>
   <tag></tag>
   <elementGuidId>46fafb4d-9fea-456f-a211-2549affb01ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAceptar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAceptar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab720cf6-18aa-48e7-b6fb-e7ce81f68337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>51adecb8-b1cf-47d2-befe-e72776612561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAceptar</value>
      <webElementGuid>9723e571-16b3-463c-8ff8-0b3023309e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAceptar</value>
      <webElementGuid>f20b8708-a015-456c-b646-5b16331139cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonAceptarSolidario</value>
      <webElementGuid>74359696-973b-47b2-8e69-6e0f82a2ac1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAceptar&quot;)</value>
      <webElementGuid>c46eac84-9af3-4174-8e43-49bb0f8382b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MicroWeb Flujo Normal Ok/Page_Resumen/iframe</value>
      <webElementGuid>edd71a9a-ba69-4f8d-9de8-7deb1a687c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAceptar']</value>
      <webElementGuid>e8f14acc-4c13-4604-89ff-6f3bc1c1453e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SelSeg']/div/div[3]/div[2]/input</value>
      <webElementGuid>eaf76dcf-ef1f-4a66-804c-f5f5ca832a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0df26640-bc3f-45e7-980a-0eaf03f2c628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnAceptar' and @id = 'btnAceptar']</value>
      <webElementGuid>91003162-4b20-466b-8d58-aea97cb1d0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
