<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Todos los campos  son obligatorios_bt_3b7b65</name>
   <tag></tag>
   <elementGuidId>92fa6253-00dd-493b-835c-8b459fd1ac7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAceptar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAceptar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd618394-8d42-44f8-8288-a8bddaeafbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>871cc437-aa53-45f8-b9da-70c018e3c21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAceptar</value>
      <webElementGuid>36e766ad-0b6f-4679-b888-58ba4db8ec82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAceptar</value>
      <webElementGuid>5ad0c7b2-13fd-4ef7-9f35-fa97e988d80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>botonAceptarSolidario</value>
      <webElementGuid>be869842-9839-44ef-bb47-679ac98e84bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarClaveOTP();</value>
      <webElementGuid>dca8b455-1d08-4e82-aacd-5fbc621df26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAceptar&quot;)</value>
      <webElementGuid>dd03583b-17c1-4a9f-a706-cda1730c9d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MicroWeb Flujo Normal Ok/Page_Resumen/iframe</value>
      <webElementGuid>faa3749e-013d-4037-add8-17391743cd21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAceptar']</value>
      <webElementGuid>47174cf5-9159-4e41-b386-d39bac64e54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='UsuarioW']/div/div[3]/div/input</value>
      <webElementGuid>e4cc7019-d08f-4f75-bbf0-ccc592d1b176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>0cf4971a-8a11-4e41-b7d0-8b72cea09665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnAceptar' and @id = 'btnAceptar']</value>
      <webElementGuid>9e333bf5-8d7f-4d5d-866e-78645c1e2192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
