<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1</name>
   <tag></tag>
   <elementGuidId>e6136a77-59c1-496e-9da6-4b0aadd03149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;next&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20f6f815-af2a-4a15-92d5-5405557a2972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b27e954b-29b2-419c-8603-ffd86dc60a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>9409b87b-3dfc-4fb9-965b-1b20c74bd580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next action-button btn btn-Solidario</value>
      <webElementGuid>b48c70e1-a311-4c08-83ac-42a5f6ac42b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>MostrarMensajeInicial(false);</value>
      <webElementGuid>ec689fce-f801-45f8-991a-f234d41248b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>2c59eb40-a4b9-43ca-9273-58ac06f0e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FrmDatosFinancieros&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 p-0&quot;]/div[@class=&quot;card px-3 pt-0 pb-0 mt-0 mb-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 mx-0&quot;]/fieldset[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/button[@class=&quot;next action-button btn btn-Solidario&quot;]</value>
      <webElementGuid>a9ebd764-0b26-469a-be25-578255d7770d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='next']</value>
      <webElementGuid>e05c1c8f-599b-4d9d-944a-a0c10d49ba8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosFinancieros']/div/div/div/div/div/fieldset/div[2]/div/button</value>
      <webElementGuid>6238d053-cd87-45a3-a06c-b4d18d093857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tus gastos mensuales'])[1]/following::button[1]</value>
      <webElementGuid>464e7ce1-6fdc-4405-b323-d416fcd38968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CERRAR'])[1]/preceding::button[2]</value>
      <webElementGuid>c98a29e4-b957-4897-bb10-6f0e63d67e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿ESTÁS SEGURO DE SALIR Y NO OBTENER TU CRÉDITO?'])[1]/preceding::button[3]</value>
      <webElementGuid>3200517e-2a55-4c22-9353-e6eb5b4b385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>2955b5e7-b682-4765-85d3-bb02c29f8ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'next' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>0098491c-000f-4ee7-9f71-5dbb43cb2bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
