<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referencia Personal_ReferenciaPersona_ebf4ce</name>
   <tag></tag>
   <elementGuidId>49d04fbe-56d1-4191-87ac-032c1cbd5736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReferenciaPersonal_PrimerNombre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReferenciaPersonal_PrimerNombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3dc4c5d-810f-4a98-beea-890ec8f9ab22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dfc3f763-baa3-4f38-ad8e-de5bb453cced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f51f53c5-3ad6-4567-8925-a5b6d12e57b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>No ingresar más de 32 caracteres</value>
      <webElementGuid>adeae54a-1f93-471d-98b8-75dbce30575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>883d7ef3-2759-43fe-bbf5-2274aa70379f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Primer nombre es requerido</value>
      <webElementGuid>f7c9d32d-1cd1-4c78-a204-176c040777d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReferenciaPersonal_PrimerNombre</value>
      <webElementGuid>d8001560-9c0b-4e3b-91ed-2c822e68ede6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>6e5d2dd5-4d4b-4dff-b7cd-a204e1e93f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReferenciaPersonal.PrimerNombre</value>
      <webElementGuid>d417ee77-7a68-43d6-9ef7-e779a2dab934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>onlyLetters(event)</value>
      <webElementGuid>967faeb6-75da-4a9a-8503-fe18f42af47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Primer nombre</value>
      <webElementGuid>82858563-4e65-4b9a-becd-5c620bc0f881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9164d8d5-a4f2-410d-88f0-feff251fe957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>405a5765-8067-41a1-ad58-92884d6b67c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReferenciaPersonal_PrimerNombre&quot;)</value>
      <webElementGuid>0c076f4a-54d4-4f26-8f0e-18a03eec70e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReferenciaPersonal_PrimerNombre']</value>
      <webElementGuid>ffdbce05-c1b7-48ec-84ee-8b327ef4450e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosPersonalesLaborales']/div/div/div/div/div/fieldset/div/div[11]/div/div/input</value>
      <webElementGuid>40c6b149-2c7a-4a67-99a0-1cb367bbdcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>9bde7e45-6200-4b5d-947b-22722d22e922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReferenciaPersonal_PrimerNombre' and @name = 'ReferenciaPersonal.PrimerNombre' and @placeholder = 'Primer nombre' and @type = 'text']</value>
      <webElementGuid>d6e4e141-a8c9-423e-8513-b296e6d65b98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
