<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tus gastos mensuales_GasEducacion</name>
   <tag></tag>
   <elementGuidId>a3db39b9-016d-4f75-bb9d-2c0e352eebd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GasEducacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GasEducacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22e98689-5211-493e-9a76-56316952b120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0231acf-9970-4308-8432-b519eae2efb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2d615c9-1b6a-4f94-a8db-645100ce1345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Educación must be a number.</value>
      <webElementGuid>277c4b29-93a8-471b-b8b2-24bb698c37a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Educación field is required.</value>
      <webElementGuid>9a28c6a6-fb08-4c98-a64d-e1c4207aa3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GasEducacion</value>
      <webElementGuid>2435ca36-7c0f-408b-a85a-1ed0619f3a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d0122bfc-c3b5-4450-b7a8-6e5eff608c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GasEducacion</value>
      <webElementGuid>202f9168-5baa-4b83-a770-32c2da2c787c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return filterFloat(event,this);</value>
      <webElementGuid>dc25b3fc-d570-4a4a-84fc-7c915ad82e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$ Educación</value>
      <webElementGuid>a1939b8a-ee18-4239-8488-0dcd4c594e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fcfe3f9-d352-49c3-b247-968e43b65691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GasEducacion&quot;)</value>
      <webElementGuid>3318056a-968a-408b-a1b6-7fe74441084b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GasEducacion']</value>
      <webElementGuid>e6e2677f-2c40-4c56-8e7e-44cda93cd9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosFinancieros']/div/div/div/div/div/fieldset/div/div[9]/div[2]/div/input</value>
      <webElementGuid>9c98f6c0-09f3-43af-aba6-d3448c584c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>06ca4204-2eea-4af2-8b74-499d557811b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GasEducacion' and @name = 'GasEducacion' and @placeholder = '$ Educación' and @type = 'text']</value>
      <webElementGuid>2c286cff-7e58-4340-a795-290b0ceb0f37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
