<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tus ingresos mensuales_RadioFondos</name>
   <tag></tag>
   <elementGuidId>825d3d00-c02b-4ca4-b2fd-3f1c3ffd9fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rbtFondos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rbtFondos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ae50462-731f-4d10-8e5d-fcbc77ca649f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c19d03b2-3f51-4dd4-b042-478de4c7b27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c4e5207c-636a-4729-a66d-988f54f57380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AceptarDeclaracion();</value>
      <webElementGuid>428204ea-a693-4371-a069-d370da4e9182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1dcd75ab-ecca-4e54-92b9-b74fc92594e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RadioFondos</value>
      <webElementGuid>145e0f42-ab4e-4dd0-847a-ed2d11ee9233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rbtFondos</value>
      <webElementGuid>1beda24c-4d81-4ad4-a59c-b68a2d26f505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rbtFondos&quot;)</value>
      <webElementGuid>0c5eaa27-f152-4dcf-a798-d3a71045fde0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rbtFondos']</value>
      <webElementGuid>e5f9824a-5072-487f-a9d7-6f1309a44eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FrmDatosFinancieros']/div/div/div/div/div/fieldset/div/div[5]/div[3]/div/input</value>
      <webElementGuid>7f1ae68a-76be-46db-a0d0-7d56f33becd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>65049592-192b-4b05-b433-69b4c903bd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RadioFondos' and @id = 'rbtFondos']</value>
      <webElementGuid>397f08f2-4d58-457a-a910-cf26a757d56a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
