<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DATOS PERSONALES Y LABORALES_personal</name>
   <tag></tag>
   <elementGuidId>f434888e-1668-4dc2-871d-bcb2a1feadab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='personal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>02c364bd-ab60-485f-993c-bd514e91d0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>71a29896-4bb1-49eb-9ea3-f9ddd9d0cf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal</value>
      <webElementGuid>b7083028-1673-4336-91b7-01fd6595b34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal&quot;)</value>
      <webElementGuid>bea41107-15b6-4e06-9e2f-28954e4c1e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='personal']</value>
      <webElementGuid>fca35f08-697c-41dc-bf7a-1342dafdeebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='progressbar']/li[2]</value>
      <webElementGuid>1e732f4d-fe0b-4f47-a38d-b70ad3faa2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>37cb6241-fe0a-4f5a-a3bb-0b378183754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'personal']</value>
      <webElementGuid>4576807a-58f5-4d00-8a90-8d11e92748fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
