<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ofertar</name>
   <tag></tag>
   <elementGuidId>83840e2e-514c-4fcc-8039-44659da44a90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.oferta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40433388-926b-4895-9291-67e17fc52a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3d32cef-c3d4-4d2e-9a3e-11cb0cb624d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success oferta</value>
      <webElementGuid>9a50ca86-fe54-4e76-adf5-37e4f7890286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PresentarOfertasGeneradas('Empaquetado', 2500.00, 36, 105.54, 900.00, 'OFEREMPA', true);</value>
      <webElementGuid>9989ee6b-aa6f-465e-984e-a339da17eee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc71c90c-1489-43e3-991f-6fb416e07990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ofertar</value>
      <webElementGuid>c9af592a-7e7d-4782-96e5-79f8608e163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementosOfertas&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;box box-default&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;info-box&quot;]/div[@class=&quot;info-box-content&quot;]/span[@class=&quot;info-box-number&quot;]/span[1]/button[@class=&quot;btn btn-success oferta&quot;]</value>
      <webElementGuid>247612ca-2746-4a6a-81e7-50aed183611f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>47bcb881-ca11-4568-9723-a2bedd8008d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementosOfertas']/div/div/div[2]/div/div/span[4]/span/button</value>
      <webElementGuid>7284cb92-8907-4f83-91cd-de7d0d3b37d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alia'])[1]/following::button[1]</value>
      <webElementGuid>24453439-cc20-4337-acca-7f26e6dc8ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UniCrédito Inmediato'])[1]/preceding::button[1]</value>
      <webElementGuid>41a0a6fb-ba33-4886-a04b-c3cfa5208296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ofertar']/parent::*</value>
      <webElementGuid>710d0173-4a8d-4218-af66-1d2fb0614c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>f9750fd8-b69b-4902-acc9-7d41b3d6af85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ofertar' or . = 'Ofertar')]</value>
      <webElementGuid>148828c1-e701-470f-a3e8-999a4a358224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
