<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generar Oferta</name>
   <tag></tag>
   <elementGuidId>627ca7fc-3913-4295-846a-184ec033ce6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#botonGenerarOfertas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='botonGenerarOfertas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fbff3ab-247a-4d58-a839-f3e3b5f6c26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ad88089-6f39-4f28-8167-b52262852157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonGenerarOfertas</value>
      <webElementGuid>393160e6-eff1-407d-848b-25cf1904d998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>00b665a1-ca50-4427-98c1-c0d9416e08b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f86968d-cfbc-4daf-8b54-714fe03cf3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar Oferta</value>
      <webElementGuid>c1106a62-c34e-48a1-8f8d-efb566bac401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botonGenerarOfertas&quot;)</value>
      <webElementGuid>a052f079-4f1f-4727-90b7-1884efbffd3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='botonGenerarOfertas']</value>
      <webElementGuid>e0c477a3-018d-401b-a7ea-5ea9b2f93257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultadosCliente']/div[3]/button</value>
      <webElementGuid>76361abf-b3a6-47c5-8efc-8526a277781d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/following::button[1]</value>
      <webElementGuid>1a909b19-6c89-4c63-adf9-cf9a8c26d5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras Cuotas'])[2]/following::button[1]</value>
      <webElementGuid>f4051c2b-acb1-4d80-bc48-4b1045e62703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operación UC Activa'])[1]/preceding::button[1]</value>
      <webElementGuid>c8f411b1-2769-4e32-95fd-9628bf7d4ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALDO OPERACIÓN UC ACTIVA'])[1]/preceding::button[2]</value>
      <webElementGuid>315b51c9-7716-4b08-8c2a-37ab62dc982c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar Oferta']/parent::*</value>
      <webElementGuid>b329f6c3-752c-4b4f-8812-f76b86b50ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/button</value>
      <webElementGuid>40b1fa7e-ff9e-4b8b-b2e0-9f088ea14ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'botonGenerarOfertas' and (text() = 'Generar Oferta' or . = 'Generar Oferta')]</value>
      <webElementGuid>bcfc6fd0-aba0-492b-b6cd-afc2c7f59375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
